// Command gensemantics generates stable audit data from the typed function
// semantic source.
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
)

func main() {
	root := flag.String("root", "internal/engine", "engine package directory")
	check := flag.Bool("check", false, "check generated output")
	flag.Parse()
	content, err := generate(*root)
	if err != nil {
		fail(err)
	}
	path := filepath.Join(*root, "semantic_roster_generated_test.go")
	if *check {
		current, readErr := os.ReadFile(path)
		if readErr != nil {
			fail(readErr)
		}
		if !bytes.Equal(current, content) {
			fail(fmt.Errorf("%s is stale; run go generate ./internal/engine", path))
		}
		return
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		fail(err)
	}
}

func generate(root string) ([]byte, error) {
	path := filepath.Join(root, "registry.go")
	files := token.NewFileSet()
	file, err := parser.ParseFile(files, path, nil, 0)
	if err != nil {
		return nil, err
	}
	var names []string
	families := make(map[string]string)
	var semanticSource bytes.Buffer
	ast.Inspect(file, func(node ast.Node) bool {
		decl, ok := node.(*ast.ValueSpec)
		if !ok || len(decl.Names) != 1 || decl.Names[0].Name != "functionSemanticSpecs" || len(decl.Values) != 1 {
			return true
		}
		literal, ok := decl.Values[0].(*ast.CompositeLit)
		if !ok {
			return false
		}
		if formatErr := format.Node(&semanticSource, files, literal); formatErr != nil {
			err = formatErr
			return false
		}
		for _, element := range literal.Elts {
			item, ok := element.(*ast.KeyValueExpr)
			if !ok {
				continue
			}
			key, ok := item.Key.(*ast.BasicLit)
			if !ok || key.Kind != token.STRING {
				continue
			}
			name, unquoteErr := strconv.Unquote(key.Value)
			if unquoteErr == nil {
				names = append(names, name)
				entry, entryOK := item.Value.(*ast.CompositeLit)
				if !entryOK {
					if call, callOK := item.Value.(*ast.CallExpr); callOK {
						if helper, helperOK := call.Fun.(*ast.Ident); helperOK &&
							(helper.Name == "higherOrderSpecialSpec" || helper.Name == "higherOrderPartialSortSpec") {
							families[name] = semanticFamilyDisplayName("semanticFamilyLambdaDedicated")
						}
					}
					continue
				}
				for _, field := range entry.Elts {
					pair, pairOK := field.(*ast.KeyValueExpr)
					if !pairOK {
						continue
					}
					fieldName, nameOK := pair.Key.(*ast.Ident)
					familyName, familyOK := pair.Value.(*ast.Ident)
					if nameOK && familyOK && fieldName.Name == "family" {
						families[name] = semanticFamilyDisplayName(familyName.Name)
					}
				}
			}
		}
		return false
	})
	if err != nil {
		return nil, err
	}
	if len(names) == 0 {
		return nil, fmt.Errorf("functionSemanticSpecs has no entries")
	}
	sort.Strings(names)

	operatorPath := filepath.Join(root, "operator_catalog.go")
	operatorFile, parseErr := parser.ParseFile(files, operatorPath, nil, 0)
	if parseErr != nil {
		return nil, parseErr
	}
	var operators []string
	ast.Inspect(operatorFile, func(node ast.Node) bool {
		decl, ok := node.(*ast.ValueSpec)
		if !ok || len(decl.Names) != 1 || decl.Names[0].Name != "operatorSemanticSpecs" || len(decl.Values) != 1 {
			return true
		}
		literal, ok := decl.Values[0].(*ast.CompositeLit)
		if !ok {
			return false
		}
		if formatErr := format.Node(&semanticSource, files, literal); formatErr != nil {
			err = formatErr
			return false
		}
		for _, element := range literal.Elts {
			entry, ok := element.(*ast.CompositeLit)
			if !ok {
				continue
			}
			for _, field := range entry.Elts {
				item, ok := field.(*ast.KeyValueExpr)
				if !ok {
					continue
				}
				identifier, keyOK := item.Key.(*ast.Ident)
				value, valueOK := item.Value.(*ast.BasicLit)
				if !keyOK || identifier.Name != "token" || !valueOK || value.Kind != token.STRING {
					continue
				}
				operator, unquoteErr := strconv.Unquote(value.Value)
				if unquoteErr == nil {
					operators = append(operators, operator)
				}
			}
		}
		return false
	})
	if err != nil {
		return nil, err
	}
	if len(operators) == 0 {
		return nil, fmt.Errorf("operatorSemanticSpecs has no entries")
	}
	sort.Strings(operators)
	var output bytes.Buffer
	output.WriteString("// Code generated by gensemantics. DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "package %s\n\n", file.Name.Name)
	digest := sha256.Sum256(semanticSource.Bytes())
	fmt.Fprintf(&output, "const generatedSemanticDigest = %q\n\n", fmt.Sprintf("%x", digest))
	output.WriteString("// generatedFunctionAuditRoster lists each static semantic source entry for tests.\n")
	output.WriteString("var generatedFunctionAuditRoster = []string{\n")
	for _, name := range names {
		fmt.Fprintf(&output, "\t%q,\n", name)
	}
	output.WriteString("}\n")
	output.WriteString("\n// generatedFunctionSemanticFamilies assigns one reusable family to each static function.\n")
	output.WriteString("var generatedFunctionSemanticFamilies = map[string]string{\n")
	for _, name := range names {
		family := families[name]
		if family == "" {
			return nil, fmt.Errorf("function %s has no generated semantic family", name)
		}
		fmt.Fprintf(&output, "\t%q: %q,\n", name, family)
	}
	output.WriteString("}\n")
	output.WriteString("\n// generatedOperatorAuditRoster lists each operator semantic source entry.\n")
	output.WriteString("var generatedOperatorAuditRoster = []string{\n")
	for _, operator := range operators {
		fmt.Fprintf(&output, "\t%q,\n", operator)
	}
	output.WriteString("}\n")
	return format.Source(output.Bytes())
}

func semanticFamilyDisplayName(identifier string) string {
	return map[string]string{
		"semanticFamilyFixedResult":                    "fixed-result-scalar",
		"semanticFamilyFirstArgument":                  "first-argument-scalar",
		"semanticFamilyCommonSupertype":                "common-supertype-scalar",
		"semanticFamilyPredicate":                      "predicate-scalar",
		"semanticFamilyConversion":                     "conversion-scalar",
		"semanticFamilyAggregateFixedResult":           "fixed-result-aggregate",
		"semanticFamilyAggregateFixedResultParametric": "fixed-result-parametric-aggregate",
		"semanticFamilyAggregateFirstArgument":         "first-argument-aggregate",
		"semanticFamilyAggregateDedicated":             "dedicated-aggregate",
		"semanticFamilyAggregateDedicatedParametric":   "dedicated-parametric-aggregate",
		"semanticFamilyWindowFixedResult":              "fixed-result-window",
		"semanticFamilyWindowFirstArgument":            "first-argument-window",
		"semanticFamilyLambdaPredicate":                "predicate-lambda",
		"semanticFamilyLambdaFirstArgument":            "first-argument-lambda",
		"semanticFamilyLambdaDedicated":                "dedicated-lambda",
		"semanticFamilyParametric":                     "parametric-scalar",
		"semanticFamilyContextDependent":               "context-dependent-scalar",
		"semanticFamilyDedicated":                      "dedicated-scalar",
	}[identifier]
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
