// Code generated by chgen; DO NOT EDIT.
//
// The ClickHouse type rules that made this file were measured on
// ClickHouse 25.8.29.51. Another major version can answer a
// different type. chgen works offline and cannot read the version of
// your server, thus this line tells you and enforces nothing.

package golden

import (
	"context"
	"errors"
	"fmt"

	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
)

// ErrNoRows is returned by a :one query when ClickHouse returns no row.
var ErrNoRows = errors.New("no rows")

// Queries is the generated ClickHouse query set. The target database is a
// connection property (clickhouse Auth.Database); the SQL never names it.
type Queries struct {
	conn driver.Conn
}

// Querier is the generated query-set contract used by services and tests.
type Querier interface {
	ReadWrappers(ctx context.Context, arg ReadWrappersParams) (ReadWrappersRow, error)
	ReadWrapperExpressions(ctx context.Context, arg ReadWrapperExpressionsParams) ([]ReadWrapperExpressionsRow, error)
}

// MockQuerier is a dependency-free test double for the generated query set.
// Set only the Func fields needed by a test; an unset field returns an error.
type MockQuerier struct {
	ReadWrappersFunc           func(ctx context.Context, arg ReadWrappersParams) (ReadWrappersRow, error)
	ReadWrapperExpressionsFunc func(ctx context.Context, arg ReadWrapperExpressionsParams) ([]ReadWrapperExpressionsRow, error)
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*MockQuerier)(nil)

func (m *MockQuerier) ReadWrappers(ctx context.Context, arg ReadWrappersParams) (ReadWrappersRow, error) {
	if m == nil || m.ReadWrappersFunc == nil {
		var zero ReadWrappersRow
		return zero, fmt.Errorf("MockQuerier.ReadWrappersFunc is nil")
	}
	return m.ReadWrappersFunc(ctx, arg)
}

func (m *MockQuerier) ReadWrapperExpressions(ctx context.Context, arg ReadWrapperExpressionsParams) ([]ReadWrapperExpressionsRow, error) {
	if m == nil || m.ReadWrapperExpressionsFunc == nil {
		return nil, fmt.Errorf("MockQuerier.ReadWrapperExpressionsFunc is nil")
	}
	return m.ReadWrapperExpressionsFunc(ctx, arg)
}

// New constructs the generated query set. It panics on a nil connection so a
// wiring mistake fails at start time, not on the first query.
func New(conn driver.Conn) *Queries {
	if conn == nil {
		panic("golden.New: ClickHouse connection is nil")
	}
	return &Queries{conn: conn}
}

// ReadWrappersRow is one row returned by ReadWrappers.
type ReadWrappersRow struct {
	Plain                  string
	Nullable               *string
	LowCardinality         string
	LowCardinalityNullable *string
	NullableInt            *int32
	NullableArrayElement   []*string
	NullableMapValue       map[string]*uint64
}

// ReadWrappersParams contains the positional arguments for ReadWrappers.
type ReadWrappersParams struct {
	ID uint64
}

const readWrappersSQL = `SELECT
    s     AS plain,
    ns    AS nullable,
    lc    AS low_cardinality,
    lcn   AS low_cardinality_nullable,
    ni32  AS nullable_int,
    arr   AS nullable_array_element,
    attrs AS nullable_map_value
FROM wrapper_probe
WHERE id = ?;`

// ReadWrappers returns one typed ClickHouse row.
func (q *Queries) ReadWrappers(ctx context.Context, arg ReadWrappersParams) (ReadWrappersRow, error) {
	var result ReadWrappersRow
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, readWrappersSQL, arg.ID)
	if err != nil {
		return result, fmt.Errorf("ReadWrappers query: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, fmt.Errorf("ReadWrappers rows: %w", err)
		}
		return result, fmt.Errorf("ReadWrappers: %w", ErrNoRows)
	}
	if err := rows.Scan(&result.Plain, &result.Nullable, &result.LowCardinality, &result.LowCardinalityNullable, &result.NullableInt, &result.NullableArrayElement, &result.NullableMapValue); err != nil {
		return result, fmt.Errorf("ReadWrappers scan: %w", err)
	}
	return result, nil
}

// ReadWrapperExpressionsRow is one row returned by ReadWrapperExpressions.
type ReadWrapperExpressionsRow struct {
	UpperLowCardinality         string
	UpperLowCardinalityNullable *string
	IfNull                      string
}

// ReadWrapperExpressionsParams contains the positional arguments for ReadWrapperExpressions.
type ReadWrapperExpressionsParams struct {
	ID uint64
}

const readWrapperExpressionsSQL = `SELECT
    upper(lc)      AS upper_low_cardinality,
    upper(lcn)     AS upper_low_cardinality_nullable,
    ifNull(ns, s)  AS if_null
FROM wrapper_probe
WHERE id = ?;`

// ReadWrapperExpressions returns typed ClickHouse rows.
func (q *Queries) ReadWrapperExpressions(ctx context.Context, arg ReadWrapperExpressionsParams) ([]ReadWrapperExpressionsRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, readWrapperExpressionsSQL, arg.ID)
	if err != nil {
		return nil, fmt.Errorf("ReadWrapperExpressions query: %w", err)
	}
	defer rows.Close()
	result := make([]ReadWrapperExpressionsRow, 0)
	var row ReadWrapperExpressionsRow
	for rows.Next() {
		row = ReadWrapperExpressionsRow{}
		if err := rows.Scan(&row.UpperLowCardinality, &row.UpperLowCardinalityNullable, &row.IfNull); err != nil {
			return nil, fmt.Errorf("ReadWrapperExpressions scan: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ReadWrapperExpressions rows: %w", err)
	}
	return result, nil
}
