// Code generated by chgen; DO NOT EDIT.
//
// The ClickHouse type rules that made this file were measured on
// ClickHouse 25.8.29.51. Another major version can answer a
// different type. chgen works offline and cannot read the version of
// your server, thus this line tells you and enforces nothing.

package golden

import (
	"context"
	"fmt"

	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
)

// Queries is the generated ClickHouse query set. The target database is a
// connection property (clickhouse Auth.Database); the SQL never names it.
type Queries struct {
	conn driver.Conn
}

// Querier is the generated query-set contract used by services and tests.
type Querier interface {
	InsertAuditRowWithDefault(ctx context.Context, arg InsertAuditRowWithDefaultParams) error
}

// MockQuerier is a dependency-free test double for the generated query set.
// Set only the Func fields needed by a test; an unset field returns an error.
type MockQuerier struct {
	InsertAuditRowWithDefaultFunc func(ctx context.Context, arg InsertAuditRowWithDefaultParams) error
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*MockQuerier)(nil)

func (m *MockQuerier) InsertAuditRowWithDefault(ctx context.Context, arg InsertAuditRowWithDefaultParams) error {
	if m == nil || m.InsertAuditRowWithDefaultFunc == nil {
		return fmt.Errorf("MockQuerier.InsertAuditRowWithDefaultFunc is nil")
	}
	return m.InsertAuditRowWithDefaultFunc(ctx, arg)
}

// New constructs the generated query set. It panics on a nil connection so a
// wiring mistake fails at start time, not on the first query.
func New(conn driver.Conn) *Queries {
	if conn == nil {
		panic("golden.New: ClickHouse connection is nil")
	}
	return &Queries{conn: conn}
}
func chgenNullableParam[T any](value *T) any {
	if value == nil {
		return nil
	}
	return *value
}

// InsertAuditRowWithDefaultParams contains the positional arguments for InsertAuditRowWithDefault.
type InsertAuditRowWithDefaultParams struct {
	ID    uint64
	Actor string
	Note  *string
}

const insertAuditRowWithDefaultSQL = `INSERT INTO audit_log (id, actor, note, written_at)
VALUES (?, upper(?), ?, now64(3));`

// InsertAuditRowWithDefault executes the annotated ClickHouse statement.
func (q *Queries) InsertAuditRowWithDefault(ctx context.Context, arg InsertAuditRowWithDefaultParams) error {
	if ctx == nil {
		ctx = context.Background()
	}
	return q.conn.Exec(ctx, insertAuditRowWithDefaultSQL, arg.ID, arg.Actor, chgenNullableParam(arg.Note))
}
