// Code generated by chgen; DO NOT EDIT.
//
// The ClickHouse type rules that made this file were measured on
// ClickHouse 25.8.29.51. Another major version can answer a
// different type. chgen works offline and cannot read the version of
// your server, thus this line tells you and enforces nothing.

package golden

import (
	"context"
	"fmt"
	"net"

	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// Queries is the generated ClickHouse query set. The target database is a
// connection property (clickhouse Auth.Database); the SQL never names it.
type Queries struct {
	conn driver.Conn
}

// Querier is the generated query-set contract used by services and tests.
type Querier interface {
	ReadScalarFamilies(ctx context.Context, arg ReadScalarFamiliesParams) (ReadScalarFamiliesRow, error)
}

// MockQuerier is a dependency-free test double for the generated query set.
// Set only the Func fields needed by a test; an unset field returns an error.
type MockQuerier struct {
	ReadScalarFamiliesFunc func(ctx context.Context, arg ReadScalarFamiliesParams) (ReadScalarFamiliesRow, error)
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*MockQuerier)(nil)

func (m *MockQuerier) ReadScalarFamilies(ctx context.Context, arg ReadScalarFamiliesParams) (ReadScalarFamiliesRow, error) {
	if m == nil || m.ReadScalarFamiliesFunc == nil {
		var zero ReadScalarFamiliesRow
		return zero, fmt.Errorf("MockQuerier.ReadScalarFamiliesFunc is nil")
	}
	return m.ReadScalarFamiliesFunc(ctx, arg)
}

// New constructs the generated query set. It panics on a nil connection so a
// wiring mistake fails at start time, not on the first query.
func New(conn driver.Conn) *Queries {
	if conn == nil {
		panic("golden.New: ClickHouse connection is nil")
	}
	return &Queries{conn: conn}
}

// ReadScalarFamiliesRow is one row returned by ReadScalarFamilies.
type ReadScalarFamiliesRow struct {
	UuidValue       uuid.UUID
	DecimalValue    decimal.Decimal
	SmallDecimal    decimal.Decimal
	Enum8Value      string
	Enum16Value     string
	Ipv4Value       net.IP
	Ipv6Value       net.IP
	NullableUuid    *uuid.UUID
	NullableDecimal *decimal.Decimal
}

// ReadScalarFamiliesParams contains the positional arguments for ReadScalarFamilies.
type ReadScalarFamiliesParams struct {
	ID uuid.UUID
}

const readScalarFamiliesSQL = `SELECT
    id     AS uuid_value,
    price  AS decimal_value,
    small  AS small_decimal,
    kind   AS enum8_value,
    kind16 AS enum16_value,
    v4     AS ipv4_value,
    v6     AS ipv6_value,
    nid    AS nullable_uuid,
    nprice AS nullable_decimal
FROM scalar_probe
WHERE id = ?;`

// ReadScalarFamilies returns one typed ClickHouse row.
func (q *Queries) ReadScalarFamilies(ctx context.Context, arg ReadScalarFamiliesParams) (ReadScalarFamiliesRow, error) {
	var result ReadScalarFamiliesRow
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, readScalarFamiliesSQL, arg.ID)
	if err != nil {
		return result, fmt.Errorf("ReadScalarFamilies query: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, fmt.Errorf("ReadScalarFamilies rows: %w", err)
		}
		return result, fmt.Errorf("ReadScalarFamilies: no rows")
	}
	if err := rows.Scan(&result.UuidValue, &result.DecimalValue, &result.SmallDecimal, &result.Enum8Value, &result.Enum16Value, &result.Ipv4Value, &result.Ipv6Value, &result.NullableUuid, &result.NullableDecimal); err != nil {
		return result, fmt.Errorf("ReadScalarFamilies scan: %w", err)
	}
	return result, nil
}
