// Code generated by chgen; DO NOT EDIT.
//
// The ClickHouse type rules that made this file were measured on
// ClickHouse 25.8.29.51. Another major version can answer a
// different type. chgen works offline and cannot read the version of
// your server, thus this line tells you and enforces nothing.

package golden

import (
	"context"
	"fmt"

	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
)

// Queries is the generated ClickHouse query set. The target database is a
// connection property (clickhouse Auth.Database); the SQL never names it.
type Queries struct {
	conn driver.Conn
}

// Querier is the generated query-set contract used by services and tests.
type Querier interface {
	DeleteStaleRunJobMetricFacts(ctx context.Context, arg DeleteStaleRunJobMetricFactsParams) error
	DeleteRunAcrossCluster(ctx context.Context, arg DeleteRunAcrossClusterParams) error
}

// MockQuerier is a dependency-free test double for the generated query set.
// Set only the Func fields needed by a test; an unset field returns an error.
type MockQuerier struct {
	DeleteStaleRunJobMetricFactsFunc func(ctx context.Context, arg DeleteStaleRunJobMetricFactsParams) error
	DeleteRunAcrossClusterFunc       func(ctx context.Context, arg DeleteRunAcrossClusterParams) error
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*MockQuerier)(nil)

func (m *MockQuerier) DeleteStaleRunJobMetricFacts(ctx context.Context, arg DeleteStaleRunJobMetricFactsParams) error {
	if m == nil || m.DeleteStaleRunJobMetricFactsFunc == nil {
		return fmt.Errorf("MockQuerier.DeleteStaleRunJobMetricFactsFunc is nil")
	}
	return m.DeleteStaleRunJobMetricFactsFunc(ctx, arg)
}

func (m *MockQuerier) DeleteRunAcrossCluster(ctx context.Context, arg DeleteRunAcrossClusterParams) error {
	if m == nil || m.DeleteRunAcrossClusterFunc == nil {
		return fmt.Errorf("MockQuerier.DeleteRunAcrossClusterFunc is nil")
	}
	return m.DeleteRunAcrossClusterFunc(ctx, arg)
}

// New constructs the generated query set. It panics on a nil connection so a
// wiring mistake fails at start time, not on the first query.
func New(conn driver.Conn) *Queries {
	if conn == nil {
		panic("golden.New: ClickHouse connection is nil")
	}
	return &Queries{conn: conn}
}

// DeleteStaleRunJobMetricFactsParams contains the positional arguments for DeleteStaleRunJobMetricFacts.
type DeleteStaleRunJobMetricFactsParams struct {
	RunKeys                  []string
	RefoldStartedAtUnixMilli int64
}

const deleteStaleRunJobMetricFactsSQL = `DELETE FROM fact_job_metrics_v3
WHERE has(?, concat(repository_owner, '/', repository, '#', toString(github_workflow_run_id), '.', toString(github_workflow_run_attempt)))
  AND toUnixTimestamp64Milli(projected_at) < ?
SETTINGS lightweight_deletes_sync = 2;`

// DeleteStaleRunJobMetricFacts executes the annotated ClickHouse statement.
func (q *Queries) DeleteStaleRunJobMetricFacts(ctx context.Context, arg DeleteStaleRunJobMetricFactsParams) error {
	if ctx == nil {
		ctx = context.Background()
	}
	return q.conn.Exec(ctx, deleteStaleRunJobMetricFactsSQL, arg.RunKeys, arg.RefoldStartedAtUnixMilli)
}

// DeleteRunAcrossClusterParams contains the positional arguments for DeleteRunAcrossCluster.
type DeleteRunAcrossClusterParams struct {
	GithubWorkflowRunID uint64
}

const deleteRunAcrossClusterSQL = `DELETE FROM fact_job_metrics_v3 ON CLUSTER 'analytics'
WHERE github_workflow_run_id = ?
SETTINGS mutations_sync = 2;`

// DeleteRunAcrossCluster executes the annotated ClickHouse statement.
func (q *Queries) DeleteRunAcrossCluster(ctx context.Context, arg DeleteRunAcrossClusterParams) error {
	if ctx == nil {
		ctx = context.Background()
	}
	return q.conn.Exec(ctx, deleteRunAcrossClusterSQL, arg.GithubWorkflowRunID)
}
