package project

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/IlyaGulya/chgen/internal/engine"
)

// executionPlan contains all generated bytes and output metadata. Planning
// reads every input and generates every package before a commit can start.
type executionPlan struct {
	packages []plannedPackage
}

type plannedPackage struct {
	name            string
	output          string
	canonicalOutput string
	outputKey       string
	outputDirectory string
	directoryKey    string
	outputInfo      fs.FileInfo
	mode            fs.FileMode
	generated       []byte
	queries         []expandedInput
	schema          []expandedInput
}

type inputOrigin struct {
	packageName string
	kind        string
	entry       string
}

// Run generates every package declared in the configuration file at
// configPath. Validation and generation do not change an output. A commit
// writes and syncs a complete temporary file before it calls os.Rename. The
// replacement keeps the os.Rename semantics of the host platform. A
// cross-directory, multi-file commit cannot be one atomic operation, so an
// I/O failure during commit can replace an earlier output while a later output
// stays unchanged.
func Run(configPath string) error {
	config, err := LoadConfig(configPath)
	if err != nil {
		return err
	}
	plan, err := buildExecutionPlan(config)
	if err != nil {
		return err
	}
	return commitExecutionPlan(plan)
}

func buildExecutionPlan(config *Config) (*executionPlan, error) {
	configPath, err := canonicalExistingPath(config.Path)
	if err != nil {
		return nil, fmt.Errorf("resolve config path %q: %w", config.Path, err)
	}

	plan := &executionPlan{packages: make([]plannedPackage, len(config.Packages))}
	configKey := portableCollisionKey(configPath)
	configInfo, err := os.Stat(config.Path)
	if err != nil {
		return nil, fmt.Errorf("inspect config path %q: %w", config.Path, err)
	}
	outputs := make(map[string]string, len(config.Packages))
	outputDirectories := make(map[string]string, len(config.Packages))
	for index, pkg := range config.Packages {
		planned, err := inspectPlannedOutput(pkg)
		if err != nil {
			return nil, fmt.Errorf("package %q: %w", pkg.Name, err)
		}
		if planned.outputKey == configKey {
			return nil, fmt.Errorf("package %q: output %s is the configuration file", pkg.Name, pkg.Output)
		}
		if planned.outputInfo != nil && os.SameFile(configInfo, planned.outputInfo) {
			return nil, fmt.Errorf("package %q: output %s is the configuration file", pkg.Name, pkg.Output)
		}
		for previousIndex := 0; previousIndex < index; previousIndex++ {
			previous := plan.packages[previousIndex]
			if planned.outputInfo != nil && previous.outputInfo != nil && os.SameFile(planned.outputInfo, previous.outputInfo) {
				return nil, fmt.Errorf("packages %q and %q resolve to the same output %s", previous.name, pkg.Name, pkg.Output)
			}
		}
		if previous, exists := outputs[planned.outputKey]; exists {
			return nil, fmt.Errorf("packages %q and %q resolve to the same output %s", previous, pkg.Name, pkg.Output)
		}
		outputs[planned.outputKey] = pkg.Name

		if previous, exists := outputDirectories[planned.directoryKey]; exists {
			return nil, fmt.Errorf(
				"packages %q and %q write generated files in one directory %s; generated files repeat Queries, Querier, MockQuerier, and New declarations, so one output per directory is required",
				previous, pkg.Name, filepath.Dir(pkg.Output),
			)
		}
		outputDirectories[planned.directoryKey] = pkg.Name
		plan.packages[index] = planned
	}

	allInputs := make(map[string]inputOrigin)
	type inputRecord struct {
		input  expandedInput
		origin inputOrigin
	}
	var inputRecords []inputRecord
	for index, pkg := range config.Packages {
		schema, err := expandInputEntriesWithOperations("schema", pkg.Schema, osInputOperations)
		if err != nil {
			return nil, fmt.Errorf("package %q: %w", pkg.Name, err)
		}
		queries, err := expandInputEntriesWithOperations("queries", pkg.Queries, osInputOperations)
		if err != nil {
			return nil, fmt.Errorf("package %q: %w", pkg.Name, err)
		}
		packageInputs := make(map[string]inputOrigin, len(schema)+len(queries))
		for _, input := range schema {
			origin := inputOrigin{packageName: pkg.Name, kind: "schema", entry: input.Entry}
			inputRecords = append(inputRecords, inputRecord{input: input, origin: origin})
			packageInputs[input.Canonical] = origin
			if _, exists := allInputs[input.CollisionKey]; !exists {
				allInputs[input.CollisionKey] = origin
			}
		}
		for _, input := range queries {
			origin := inputOrigin{packageName: pkg.Name, kind: "queries", entry: input.Entry}
			inputRecords = append(inputRecords, inputRecord{input: input, origin: origin})
			previous, exists := packageInputs[input.Canonical]
			if !exists {
				for _, schemaInput := range schema {
					if schemaInput.Info != nil && input.Info != nil && os.SameFile(schemaInput.Info, input.Info) {
						previous = inputOrigin{packageName: pkg.Name, kind: "schema", entry: schemaInput.Entry}
						exists = true
						break
					}
				}
			}
			if exists {
				return nil, fmt.Errorf(
					"package %q: %s entry %q and queries entry %q select the same file %s",
					pkg.Name, previous.kind, previous.entry, input.Entry, input.Path,
				)
			}
			packageInputs[input.Canonical] = origin
			if _, exists := allInputs[input.CollisionKey]; !exists {
				allInputs[input.CollisionKey] = origin
			}
		}
		plan.packages[index].schema = schema
		plan.packages[index].queries = queries
	}
	if origin, exists := allInputs[configKey]; exists {
		return nil, fmt.Errorf(
			"configuration file %s is also %s input %q of package %q",
			config.Path, origin.kind, origin.entry, origin.packageName,
		)
	}
	for _, record := range inputRecords {
		if record.input.Info != nil && os.SameFile(configInfo, record.input.Info) {
			return nil, fmt.Errorf(
				"configuration file %s is also %s input %q of package %q",
				config.Path, record.origin.kind, record.origin.entry, record.origin.packageName,
			)
		}
	}

	for _, planned := range plan.packages {
		if origin, exists := allInputs[planned.outputKey]; exists {
			return nil, fmt.Errorf(
				"package %q: output %s is also %s input %q of package %q",
				planned.name, planned.output, origin.kind, origin.entry, origin.packageName,
			)
		}
		for _, record := range inputRecords {
			if planned.outputInfo != nil && record.input.Info != nil && os.SameFile(planned.outputInfo, record.input.Info) {
				return nil, fmt.Errorf(
					"package %q: output %s is also %s input %q of package %q",
					planned.name, planned.output, record.origin.kind, record.origin.entry, record.origin.packageName,
				)
			}
		}
	}

	for index := range plan.packages {
		planned := &plan.packages[index]
		schemaFiles := expandedInputPaths(planned.schema)
		queryFiles := expandedInputPaths(planned.queries)
		catalogs, err := engine.ParseSchemaCatalogs(schemaFiles)
		if err != nil {
			return nil, fmt.Errorf("package %q: %w", planned.name, err)
		}
		queries, err := engine.ParseQueryFiles(queryFiles, catalogs)
		if err != nil {
			return nil, fmt.Errorf("package %q: %w", planned.name, err)
		}
		generated, err := engine.Generate(planned.name, queries)
		if err != nil {
			return nil, fmt.Errorf("package %q: %w", planned.name, err)
		}
		planned.generated = generated
	}
	return plan, nil
}

func inspectPlannedOutput(pkg PackageConfig) (plannedPackage, error) {
	canonical, err := canonicalPotentialPath(pkg.Output)
	if err != nil {
		return plannedPackage{}, fmt.Errorf("resolve output %s: %w", pkg.Output, err)
	}
	base := filepath.Base(pkg.Output)
	if filepath.Ext(base) != ".go" {
		return plannedPackage{}, fmt.Errorf("output %s must have a .go file name", pkg.Output)
	}
	if strings.HasPrefix(base, ".") || strings.HasPrefix(base, "_") {
		return plannedPackage{}, fmt.Errorf("output %s has a file name that the Go tool ignores", pkg.Output)
	}
	if strings.HasSuffix(base, "_test.go") {
		return plannedPackage{}, fmt.Errorf("output %s must not be a Go test file", pkg.Output)
	}
	if suffix := goBuildFilenameSuffix(base); suffix != "" {
		return plannedPackage{}, fmt.Errorf("output %s has Go build suffix %q and would be ignored on other targets", pkg.Output, suffix)
	}
	outputDirectory, err := canonicalPotentialPath(filepath.Dir(pkg.Output))
	if err != nil {
		return plannedPackage{}, fmt.Errorf("resolve output directory %s: %w", filepath.Dir(pkg.Output), err)
	}

	mode := fs.FileMode(0)
	var outputInfo fs.FileInfo
	info, err := os.Lstat(pkg.Output)
	switch {
	case err == nil:
		// A leaf link would make replacement semantics unclear. A link in a
		// parent directory is supported and canonicalPotentialPath resolves it.
		if info.Mode()&os.ModeSymlink != 0 {
			return plannedPackage{}, fmt.Errorf("output %s is a symbolic link; output links are not supported", pkg.Output)
		}
		if !info.Mode().IsRegular() {
			return plannedPackage{}, fmt.Errorf("output %s is not a regular file", pkg.Output)
		}
		mode = info.Mode().Perm()
		outputInfo = info
	case errors.Is(err, fs.ErrNotExist):
		// The operating system applies the caller's umask to a new output.
	case errors.Is(err, fs.ErrPermission):
		return plannedPackage{}, fmt.Errorf("inspect output %s: permission denied", pkg.Output)
	default:
		return plannedPackage{}, fmt.Errorf("inspect output %s: %w", pkg.Output, err)
	}
	return plannedPackage{
		name:            pkg.Name,
		output:          pkg.Output,
		canonicalOutput: canonical,
		outputKey:       portableCollisionKey(canonical),
		outputDirectory: outputDirectory,
		directoryKey:    portableCollisionKey(outputDirectory),
		outputInfo:      outputInfo,
		mode:            mode,
	}, nil
}

var knownGOOS = map[string]bool{
	"aix": true, "android": true, "darwin": true, "dragonfly": true,
	"freebsd": true, "illumos": true, "ios": true, "js": true,
	"linux": true, "netbsd": true, "openbsd": true, "plan9": true,
	"solaris": true, "wasip1": true, "windows": true,
}

var knownGOARCH = map[string]bool{
	"386": true, "amd64": true, "arm": true, "arm64": true,
	"loong64": true, "mips": true, "mips64": true, "mips64le": true,
	"mipsle": true, "ppc64": true, "ppc64le": true, "riscv64": true,
	"s390x": true, "wasm": true,
}

func goBuildFilenameSuffix(base string) string {
	stem := strings.TrimSuffix(base, ".go")
	parts := strings.Split(stem, "_")
	if len(parts) < 2 {
		return ""
	}
	last := parts[len(parts)-1]
	if knownGOOS[last] || knownGOARCH[last] {
		return last
	}
	return ""
}

func canonicalPotentialPath(path string) (string, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	abs = filepath.Clean(abs)
	current := abs
	var suffix []string
	for {
		_, err := os.Lstat(current)
		switch {
		case err == nil:
			resolved, err := filepath.EvalSymlinks(current)
			if err != nil {
				return "", err
			}
			for index := len(suffix) - 1; index >= 0; index-- {
				resolved = filepath.Join(resolved, suffix[index])
			}
			return filepath.Clean(resolved), nil
		case errors.Is(err, fs.ErrNotExist):
			parent := filepath.Dir(current)
			if parent == current {
				return "", err
			}
			suffix = append(suffix, filepath.Base(current))
			current = parent
		case errors.Is(err, fs.ErrPermission):
			return "", fmt.Errorf("permission denied")
		default:
			return "", err
		}
	}
}

func expandedInputPaths(inputs []expandedInput) []string {
	paths := make([]string, len(inputs))
	for index := range inputs {
		paths[index] = inputs[index].Path
	}
	return paths
}

type stagedOutput struct {
	planned plannedPackage
	temp    string
}

type outputFile interface {
	Name() string
	Chmod(fs.FileMode) error
	Write([]byte) (int, error)
	Sync() error
	Close() error
}

type outputOperations struct {
	mkdirAll           func(string, fs.FileMode) error
	create             func(string, fs.FileMode) (outputFile, error)
	lstat              func(string) (fs.FileInfo, error)
	rename             func(string, string) error
	remove             func(string) error
	canonicalPotential func(string) (string, error)
}

var osOutputOperations = outputOperations{
	mkdirAll:           os.MkdirAll,
	create:             createOutputTemp,
	lstat:              os.Lstat,
	rename:             os.Rename,
	remove:             os.Remove,
	canonicalPotential: canonicalPotentialPath,
}

func commitExecutionPlan(plan *executionPlan) error {
	return commitExecutionPlanWithOperations(plan, osOutputOperations)
}

func commitExecutionPlanWithOperations(plan *executionPlan, operations outputOperations) error {
	staged := make([]stagedOutput, 0, len(plan.packages))
	cleanup := func() {
		for _, output := range staged {
			if output.temp != "" {
				_ = operations.remove(output.temp)
			}
		}
	}
	defer cleanup()

	for _, planned := range plan.packages {
		directory := filepath.Dir(planned.output)
		if err := operations.mkdirAll(directory, 0o755); err != nil {
			return fmt.Errorf("create output directory for %s: %w", planned.output, err)
		}
		currentDirectory, err := operations.canonicalPotential(directory)
		if err != nil {
			return fmt.Errorf("resolve output directory for %s before staging: %w", planned.output, err)
		}
		if currentDirectory != planned.outputDirectory {
			return fmt.Errorf("output directory for %s changed after planning; refuse the commit", planned.output)
		}
		// This check runs immediately before temporary file creation. Another process can
		// change the file system after the check because Go has no portable path
		// lock for this operation.
		temp, err := stageOutputWithOperations(planned, operations)
		if err != nil {
			return err
		}
		staged = append(staged, stagedOutput{planned: planned, temp: temp})
	}

	for index := range staged {
		output := &staged[index]
		if err := refuseOutputLinkWithOperations(output.planned.output, operations); err != nil {
			return err
		}
		if err := operations.rename(output.temp, output.planned.output); err != nil {
			return fmt.Errorf("replace %s: %w", output.planned.output, err)
		}
		output.temp = ""
	}
	return nil
}

func stageOutputWithOperations(planned plannedPackage, operations outputOperations) (string, error) {
	directory := filepath.Dir(planned.output)
	temp, err := operations.create(directory, 0o666)
	if err != nil {
		return "", fmt.Errorf("create temporary output for %s: %w", planned.output, err)
	}
	tempPath := temp.Name()
	keep := false
	closeNeeded := true
	defer func() {
		if !keep {
			if closeNeeded {
				_ = temp.Close()
			}
			_ = operations.remove(tempPath)
		}
	}()
	if planned.outputInfo != nil {
		if err := temp.Chmod(planned.mode); err != nil {
			return "", fmt.Errorf("set temporary output mode for %s: %w", planned.output, err)
		}
	}
	if _, err := temp.Write(planned.generated); err != nil {
		return "", fmt.Errorf("write temporary output for %s: %w", planned.output, err)
	}
	if err := temp.Sync(); err != nil {
		return "", fmt.Errorf("sync temporary output for %s: %w", planned.output, err)
	}
	err = temp.Close()
	closeNeeded = false
	if err != nil {
		return "", fmt.Errorf("close temporary output for %s: %w", planned.output, err)
	}
	keep = true
	return tempPath, nil
}

func createOutputTemp(directory string, mode fs.FileMode) (outputFile, error) {
	for attempts := 0; attempts < 100; attempts++ {
		var randomBytes [16]byte
		if _, err := rand.Read(randomBytes[:]); err != nil {
			return nil, err
		}
		name := ".chgen-" + hex.EncodeToString(randomBytes[:]) + ".tmp"
		path := filepath.Join(directory, name)
		file, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, mode)
		if err == nil {
			return file, nil
		}
		if !errors.Is(err, fs.ErrExist) {
			return nil, err
		}
	}
	return nil, fmt.Errorf("cannot allocate a unique temporary output name")
}

func refuseOutputLinkWithOperations(path string, operations outputOperations) error {
	info, err := operations.lstat(path)
	switch {
	case err == nil && info.Mode()&os.ModeSymlink != 0:
		return fmt.Errorf("output %s became a symbolic link during generation; output links are not supported", path)
	case err == nil:
		return nil
	case errors.Is(err, fs.ErrNotExist):
		return nil
	case errors.Is(err, fs.ErrPermission):
		return fmt.Errorf("inspect output %s before replacement: permission denied", path)
	default:
		return fmt.Errorf("inspect output %s before replacement: %w", path, err)
	}
}
