// Code generated by chgen; DO NOT EDIT.
//
// The ClickHouse type rules that made this file were measured on
// ClickHouse 25.8.29.51. Another major version can answer a
// different type. chgen works offline and cannot read the version of
// your server, thus this line tells you and enforces nothing.

package golden

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
)

// ErrNoRows is returned by a :one query when ClickHouse returns no row.
var ErrNoRows = errors.New("no rows")

// Queries is the generated ClickHouse query set. The target database is a
// connection property (clickhouse Auth.Database); the SQL never names it.
type Queries struct {
	conn driver.Conn
}

// Querier is the generated query-set contract used by services and tests.
type Querier interface {
	ReadTemporalColumns(ctx context.Context, arg ReadTemporalColumnsParams) (ReadTemporalColumnsRow, error)
	ReadIntervalResults(ctx context.Context, arg ReadIntervalResultsParams) (ReadIntervalResultsRow, error)
	CountAfter(ctx context.Context, arg CountAfterParams) (CountAfterRow, error)
}

// MockQuerier is a dependency-free test double for the generated query set.
// Set only the Func fields needed by a test; an unset field returns an error.
type MockQuerier struct {
	ReadTemporalColumnsFunc func(ctx context.Context, arg ReadTemporalColumnsParams) (ReadTemporalColumnsRow, error)
	ReadIntervalResultsFunc func(ctx context.Context, arg ReadIntervalResultsParams) (ReadIntervalResultsRow, error)
	CountAfterFunc          func(ctx context.Context, arg CountAfterParams) (CountAfterRow, error)
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*MockQuerier)(nil)

func (m *MockQuerier) ReadTemporalColumns(ctx context.Context, arg ReadTemporalColumnsParams) (ReadTemporalColumnsRow, error) {
	if m == nil || m.ReadTemporalColumnsFunc == nil {
		var zero ReadTemporalColumnsRow
		return zero, fmt.Errorf("MockQuerier.ReadTemporalColumnsFunc is nil")
	}
	return m.ReadTemporalColumnsFunc(ctx, arg)
}

func (m *MockQuerier) ReadIntervalResults(ctx context.Context, arg ReadIntervalResultsParams) (ReadIntervalResultsRow, error) {
	if m == nil || m.ReadIntervalResultsFunc == nil {
		var zero ReadIntervalResultsRow
		return zero, fmt.Errorf("MockQuerier.ReadIntervalResultsFunc is nil")
	}
	return m.ReadIntervalResultsFunc(ctx, arg)
}

func (m *MockQuerier) CountAfter(ctx context.Context, arg CountAfterParams) (CountAfterRow, error) {
	if m == nil || m.CountAfterFunc == nil {
		var zero CountAfterRow
		return zero, fmt.Errorf("MockQuerier.CountAfterFunc is nil")
	}
	return m.CountAfterFunc(ctx, arg)
}

// New constructs the generated query set. It panics on a nil connection so a
// wiring mistake fails at start time, not on the first query.
func New(conn driver.Conn) *Queries {
	if conn == nil {
		panic("golden.New: ClickHouse connection is nil")
	}
	return &Queries{conn: conn}
}

// The constants below are the MEASURED range limits of the ClickHouse
// temporal types, taken from ClickHouse 25.8.29.51 through the HTTP
// interface, which does not involve the Go driver. Each limit is the last
// value that the server stores unchanged.
//
// The guards exist because clickhouse-go reports NO error for a value that
// the column cannot hold. Measured with driver v2.47.0, a DateTime64(3) write
// of 2299-12-31 stored 2106-02-07 through conn.Exec and 1900-01-01 through
// the native batch path. Both calls returned nil. The project rule is: never
// silently wrong, thus an unrepresentable value becomes an explicit error.
const (
	chgenDateMinUnix                 = int64(0)
	chgenDateMaxUnix                 = int64(5662310399)
	chgenDate32MinUnix               = int64(-2208988800)
	chgenDate32MaxUnix               = int64(10413791999)
	chgenDateTimeMinUnix             = int64(0)
	chgenDateTimeMaxUnix             = int64(4294967295)
	chgenDateTime64MinUnix           = int64(-2208988800)
	chgenDateTime64MaxUnix           = int64(9223372036)
	chgenDateTime64MaxNanosecond     = int64(854775807)
	chgenDateTime64NanoMinUnix       = int64(-2208988800)
	chgenDateTime64NanoMaxUnix       = int64(9223372036)
	chgenDateTime64NanoMaxNanosecond = int64(854775807)
)

func chgenGuardRange(value time.Time, label, typeName string, minUnix, maxUnix int64) error {
	seconds := value.Unix()
	if seconds < minUnix || seconds > maxUnix {
		return fmt.Errorf(
			"%s: %s cannot hold %s; the representable range is %s to %s",
			label,
			typeName,
			value.UTC().Format(time.RFC3339Nano),
			time.Unix(minUnix, 0).UTC().Format(time.RFC3339),
			time.Unix(maxUnix, 0).UTC().Format(time.RFC3339),
		)
	}
	return nil
}

func chgenGuardDateTime64Range(value time.Time, label, typeName string, minUnix, maxUnix, maxNanosecond int64) error {
	seconds := value.Unix()
	nanosecond := int64(value.Nanosecond())
	if seconds < minUnix || seconds > maxUnix || (seconds == maxUnix && nanosecond > maxNanosecond) {
		return fmt.Errorf(
			"%s: %s cannot hold %s; the representable range is %s to %s",
			label,
			typeName,
			value.UTC().Format(time.RFC3339Nano),
			time.Unix(minUnix, 0).UTC().Format(time.RFC3339),
			time.Unix(maxUnix, maxNanosecond).UTC().Format(time.RFC3339Nano),
		)
	}
	return nil
}

func chgenGuardDate(value time.Time, label string) error {
	return chgenGuardRange(value, label, "Date", chgenDateMinUnix, chgenDateMaxUnix)
}

func chgenGuardDate32(value time.Time, label string) error {
	return chgenGuardRange(value, label, "Date32", chgenDate32MinUnix, chgenDate32MaxUnix)
}

func chgenGuardDateTime(value time.Time, label string) error {
	return chgenGuardRange(value, label, "DateTime", chgenDateTimeMinUnix, chgenDateTimeMaxUnix)
}

// chgenGuardDateTime64 uses the DRIVER limit, not the wider column calendar.
// A DateTime64(3) column holds up to 2299-12-31, but clickhouse-go carries
// every DateTime64 through int64 nanoseconds, so a write of 2299-12-31 stored
// 1900-01-01 00:00:00.291 with err = nil (measured, v2.47.0). Guarding at the
// column limit would pass exactly the values that corrupt.
func chgenGuardDateTime64(value time.Time, label string) error {
	return chgenGuardDateTime64Range(value, label, "DateTime64 through clickhouse-go", chgenDateTime64MinUnix, chgenDateTime64MaxUnix, chgenDateTime64MaxNanosecond)
}

// chgenGuardDateTime64Nano is precision 9, where the server itself raises
// DECIMAL_OVERFLOW past the same nanosecond limit.
func chgenGuardDateTime64Nano(value time.Time, label string) error {
	return chgenGuardDateTime64Range(value, label, "DateTime64(9)", chgenDateTime64NanoMinUnix, chgenDateTime64NanoMaxUnix, chgenDateTime64NanoMaxNanosecond)
}

// chgenCheckScannedTime rejects a DateTime64 that the driver could not carry.
// clickhouse-go converts every DateTime64 through int64 nanoseconds. A stored
// instant after 2262-04-11T23:47:16.854775807Z can arrive as an unrelated
// earlier time with no error. Measured: a stored 2299-12-31 arrives as
// 1715-06-12.
//
// The arriving value does not identify the original instant. This check can
// only refuse the invalid scan. It cannot repair the value.
func chgenCheckScannedTime(value time.Time, label string) error {
	if value.Unix() < chgenReadableMinUnix {
		return fmt.Errorf(
			"%s: the scanned DateTime64 %s is before %s, which means the driver wrapped a stored value that is beyond %s; the value cannot be recovered",
			label,
			value.UTC().Format(time.RFC3339Nano),
			time.Unix(chgenReadableMinUnix, 0).UTC().Format(time.RFC3339),
			time.Unix(chgenReadableMaxUnix, chgenReadableMaxNanosecond).UTC().Format(time.RFC3339Nano),
		)
	}
	return nil
}

const (
	chgenReadableMinUnix       = int64(-2208988800)
	chgenReadableMaxUnix       = int64(9223372036)
	chgenReadableMaxNanosecond = int64(854775807)
)

// ReadTemporalColumnsRow is one row returned by ReadTemporalColumns.
type ReadTemporalColumnsRow struct {
	Day           time.Time
	WideDay       time.Time
	Second        time.Time
	SecondUtc     time.Time
	Milli         time.Time
	MicroUtc      time.Time
	NullableMilli *time.Time
}

// ReadTemporalColumnsParams contains the positional arguments for ReadTemporalColumns.
type ReadTemporalColumnsParams struct {
	ID uint64
}

const readTemporalColumnsSQL = `SELECT
    d     AS day,
    d32   AS wide_day,
    dt    AS second,
    dtz   AS second_utc,
    dt64  AS milli,
    dtz64 AS micro_utc,
    ndt64 AS nullable_milli
FROM temporal_probe
WHERE id = ?;`

// ReadTemporalColumns returns one typed ClickHouse row.
func (q *Queries) ReadTemporalColumns(ctx context.Context, arg ReadTemporalColumnsParams) (ReadTemporalColumnsRow, error) {
	var result ReadTemporalColumnsRow
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, readTemporalColumnsSQL, arg.ID)
	if err != nil {
		return result, fmt.Errorf("ReadTemporalColumns query: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, fmt.Errorf("ReadTemporalColumns rows: %w", err)
		}
		return result, fmt.Errorf("ReadTemporalColumns: %w", ErrNoRows)
	}
	if err := rows.Scan(&result.Day, &result.WideDay, &result.Second, &result.SecondUtc, &result.Milli, &result.MicroUtc, &result.NullableMilli); err != nil {
		return result, fmt.Errorf("ReadTemporalColumns scan: %w", err)
	}
	if err := chgenCheckScannedTime(result.Milli, "Milli"); err != nil {
		return result, fmt.Errorf("ReadTemporalColumns: %w", err)
	}
	if err := chgenCheckScannedTime(result.MicroUtc, "MicroUtc"); err != nil {
		return result, fmt.Errorf("ReadTemporalColumns: %w", err)
	}
	if result.NullableMilli != nil {
		if err := chgenCheckScannedTime((*result.NullableMilli), "NullableMilli"); err != nil {
			return result, fmt.Errorf("ReadTemporalColumns: %w", err)
		}
	}
	return result, nil
}

// ReadIntervalResultsRow is one row returned by ReadIntervalResults.
type ReadIntervalResultsRow struct {
	DayPlusDay       time.Time
	DayPlusHour      time.Time
	SecondPlusMonth  time.Time
	MilliMinusSecond time.Time
	StartOfHour      time.Time
}

// ReadIntervalResultsParams contains the positional arguments for ReadIntervalResults.
type ReadIntervalResultsParams struct {
	ID uint64
}

const readIntervalResultsSQL = `SELECT
    d + INTERVAL 1 DAY     AS day_plus_day,
    d + INTERVAL 1 HOUR    AS day_plus_hour,
    dt + INTERVAL 1 MONTH  AS second_plus_month,
    dt64 - INTERVAL 5 SECOND AS milli_minus_second,
    toStartOfInterval(dt64, INTERVAL 1 HOUR) AS start_of_hour
FROM temporal_probe
WHERE id = ?;`

// ReadIntervalResults returns one typed ClickHouse row.
func (q *Queries) ReadIntervalResults(ctx context.Context, arg ReadIntervalResultsParams) (ReadIntervalResultsRow, error) {
	var result ReadIntervalResultsRow
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, readIntervalResultsSQL, arg.ID)
	if err != nil {
		return result, fmt.Errorf("ReadIntervalResults query: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, fmt.Errorf("ReadIntervalResults rows: %w", err)
		}
		return result, fmt.Errorf("ReadIntervalResults: %w", ErrNoRows)
	}
	if err := rows.Scan(&result.DayPlusDay, &result.DayPlusHour, &result.SecondPlusMonth, &result.MilliMinusSecond, &result.StartOfHour); err != nil {
		return result, fmt.Errorf("ReadIntervalResults scan: %w", err)
	}
	if err := chgenCheckScannedTime(result.MilliMinusSecond, "MilliMinusSecond"); err != nil {
		return result, fmt.Errorf("ReadIntervalResults: %w", err)
	}
	return result, nil
}

// CountAfterRow is one row returned by CountAfter.
type CountAfterRow struct {
	Total uint64
}

// CountAfterParams contains the positional arguments for CountAfter.
type CountAfterParams struct {
	Day   time.Time
	Since time.Time
}

const countAfterSQL = `SELECT count() AS total
FROM temporal_probe
WHERE d > ? AND dt64 > ?;`

// CountAfter returns one typed ClickHouse row.
func (q *Queries) CountAfter(ctx context.Context, arg CountAfterParams) (CountAfterRow, error) {
	var result CountAfterRow
	if ctx == nil {
		ctx = context.Background()
	}
	if err := chgenGuardDate(arg.Day, "Day"); err != nil {
		return result, fmt.Errorf("CountAfter: %w", err)
	}
	if err := chgenGuardDateTime64(arg.Since, "Since"); err != nil {
		return result, fmt.Errorf("CountAfter: %w", err)
	}
	rows, err := q.conn.Query(ctx, countAfterSQL, arg.Day, arg.Since)
	if err != nil {
		return result, fmt.Errorf("CountAfter query: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, fmt.Errorf("CountAfter rows: %w", err)
		}
		return result, fmt.Errorf("CountAfter: %w", ErrNoRows)
	}
	if err := rows.Scan(&result.Total); err != nil {
		return result, fmt.Errorf("CountAfter scan: %w", err)
	}
	return result, nil
}
