// Code generated by chgen; DO NOT EDIT.
//
// The ClickHouse type rules that made this file were measured on
// ClickHouse 25.8.29.51. Another major version can answer a
// different type. chgen works offline and cannot read the version of
// your server, thus this line tells you and enforces nothing.

package examplequeries

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2"
	"github.com/ClickHouse/clickhouse-go/v2/ext"
	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
)

// Queries is the generated ClickHouse query set. The target database is a
// connection property (clickhouse Auth.Database); the SQL never names it.
type Queries struct {
	conn driver.Conn
}

// Querier is the generated query-set contract used by services and tests.
type Querier interface {
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error)
	CountOrdersForCustomer(ctx context.Context, arg CountOrdersForCustomerParams) (CountOrdersForCustomerRow, error)
	ListOrdersByOptionalDiscount(ctx context.Context, arg ListOrdersByOptionalDiscountParams) ([]ListOrdersByOptionalDiscountRow, error)
	DrainOrderEvents(ctx context.Context, arg DrainOrderEventsParams) ([]DrainOrderEventsRow, error)
	ListCustomerActivity(ctx context.Context, arg ListCustomerActivityParams) ([]ListCustomerActivityRow, error)
	ListOrdersForKeys(ctx context.Context, arg ListOrdersForKeysParams) ([]ListOrdersForKeysRow, error)
	ListOrdersIncludedExcluded(ctx context.Context, arg ListOrdersIncludedExcludedParams) ([]ListOrdersIncludedExcludedRow, error)
	ListOrdersForKeysWithHint(ctx context.Context, arg ListOrdersForKeysWithHintParams) ([]ListOrdersForKeysWithHintRow, error)
	ListTopCountries(ctx context.Context, arg ListTopCountriesParams) ([]ListTopCountriesRow, error)
	ListOrdersAboveAverage(ctx context.Context, arg ListOrdersAboveAverageParams) ([]ListOrdersAboveAverageRow, error)
	InsertOrderAudit(ctx context.Context, arg InsertOrderAuditParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	DeleteOrderEventsBefore(ctx context.Context, arg DeleteOrderEventsBeforeParams) error
	RefreshCountryRollup(ctx context.Context, arg RefreshCountryRollupParams) error
	DropCountryRollupPartition(ctx context.Context, arg DropCountryRollupPartitionParams) error
	ListOrderEventPayloads(ctx context.Context, arg ListOrderEventPayloadsParams) ([]ListOrderEventPayloadsRow, error)
	ListOrdersWithLiteralMarker(ctx context.Context, arg ListOrdersWithLiteralMarkerParams) ([]ListOrdersWithLiteralMarkerRow, error)
}

// MockQuerier is a dependency-free test double for the generated query set.
// Set only the Func fields needed by a test; an unset field returns an error.
type MockQuerier struct {
	ListOrdersFunc                   func(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error)
	CountOrdersForCustomerFunc       func(ctx context.Context, arg CountOrdersForCustomerParams) (CountOrdersForCustomerRow, error)
	ListOrdersByOptionalDiscountFunc func(ctx context.Context, arg ListOrdersByOptionalDiscountParams) ([]ListOrdersByOptionalDiscountRow, error)
	DrainOrderEventsFunc             func(ctx context.Context, arg DrainOrderEventsParams) ([]DrainOrderEventsRow, error)
	ListCustomerActivityFunc         func(ctx context.Context, arg ListCustomerActivityParams) ([]ListCustomerActivityRow, error)
	ListOrdersForKeysFunc            func(ctx context.Context, arg ListOrdersForKeysParams) ([]ListOrdersForKeysRow, error)
	ListOrdersIncludedExcludedFunc   func(ctx context.Context, arg ListOrdersIncludedExcludedParams) ([]ListOrdersIncludedExcludedRow, error)
	ListOrdersForKeysWithHintFunc    func(ctx context.Context, arg ListOrdersForKeysWithHintParams) ([]ListOrdersForKeysWithHintRow, error)
	ListTopCountriesFunc             func(ctx context.Context, arg ListTopCountriesParams) ([]ListTopCountriesRow, error)
	ListOrdersAboveAverageFunc       func(ctx context.Context, arg ListOrdersAboveAverageParams) ([]ListOrdersAboveAverageRow, error)
	InsertOrderAuditFunc             func(ctx context.Context, arg InsertOrderAuditParams) error
	UpdateOrderStatusFunc            func(ctx context.Context, arg UpdateOrderStatusParams) error
	DeleteOrderEventsBeforeFunc      func(ctx context.Context, arg DeleteOrderEventsBeforeParams) error
	RefreshCountryRollupFunc         func(ctx context.Context, arg RefreshCountryRollupParams) error
	DropCountryRollupPartitionFunc   func(ctx context.Context, arg DropCountryRollupPartitionParams) error
	ListOrderEventPayloadsFunc       func(ctx context.Context, arg ListOrderEventPayloadsParams) ([]ListOrderEventPayloadsRow, error)
	ListOrdersWithLiteralMarkerFunc  func(ctx context.Context, arg ListOrdersWithLiteralMarkerParams) ([]ListOrdersWithLiteralMarkerRow, error)
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*MockQuerier)(nil)

func (m *MockQuerier) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	if m == nil || m.ListOrdersFunc == nil {
		return nil, fmt.Errorf("MockQuerier.ListOrdersFunc is nil")
	}
	return m.ListOrdersFunc(ctx, arg)
}

func (m *MockQuerier) CountOrdersForCustomer(ctx context.Context, arg CountOrdersForCustomerParams) (CountOrdersForCustomerRow, error) {
	if m == nil || m.CountOrdersForCustomerFunc == nil {
		var zero CountOrdersForCustomerRow
		return zero, fmt.Errorf("MockQuerier.CountOrdersForCustomerFunc is nil")
	}
	return m.CountOrdersForCustomerFunc(ctx, arg)
}

func (m *MockQuerier) ListOrdersByOptionalDiscount(ctx context.Context, arg ListOrdersByOptionalDiscountParams) ([]ListOrdersByOptionalDiscountRow, error) {
	if m == nil || m.ListOrdersByOptionalDiscountFunc == nil {
		return nil, fmt.Errorf("MockQuerier.ListOrdersByOptionalDiscountFunc is nil")
	}
	return m.ListOrdersByOptionalDiscountFunc(ctx, arg)
}

func (m *MockQuerier) DrainOrderEvents(ctx context.Context, arg DrainOrderEventsParams) ([]DrainOrderEventsRow, error) {
	if m == nil || m.DrainOrderEventsFunc == nil {
		return nil, fmt.Errorf("MockQuerier.DrainOrderEventsFunc is nil")
	}
	return m.DrainOrderEventsFunc(ctx, arg)
}

func (m *MockQuerier) ListCustomerActivity(ctx context.Context, arg ListCustomerActivityParams) ([]ListCustomerActivityRow, error) {
	if m == nil || m.ListCustomerActivityFunc == nil {
		return nil, fmt.Errorf("MockQuerier.ListCustomerActivityFunc is nil")
	}
	return m.ListCustomerActivityFunc(ctx, arg)
}

func (m *MockQuerier) ListOrdersForKeys(ctx context.Context, arg ListOrdersForKeysParams) ([]ListOrdersForKeysRow, error) {
	if m == nil || m.ListOrdersForKeysFunc == nil {
		return nil, fmt.Errorf("MockQuerier.ListOrdersForKeysFunc is nil")
	}
	return m.ListOrdersForKeysFunc(ctx, arg)
}

func (m *MockQuerier) ListOrdersIncludedExcluded(ctx context.Context, arg ListOrdersIncludedExcludedParams) ([]ListOrdersIncludedExcludedRow, error) {
	if m == nil || m.ListOrdersIncludedExcludedFunc == nil {
		return nil, fmt.Errorf("MockQuerier.ListOrdersIncludedExcludedFunc is nil")
	}
	return m.ListOrdersIncludedExcludedFunc(ctx, arg)
}

func (m *MockQuerier) ListOrdersForKeysWithHint(ctx context.Context, arg ListOrdersForKeysWithHintParams) ([]ListOrdersForKeysWithHintRow, error) {
	if m == nil || m.ListOrdersForKeysWithHintFunc == nil {
		return nil, fmt.Errorf("MockQuerier.ListOrdersForKeysWithHintFunc is nil")
	}
	return m.ListOrdersForKeysWithHintFunc(ctx, arg)
}

func (m *MockQuerier) ListTopCountries(ctx context.Context, arg ListTopCountriesParams) ([]ListTopCountriesRow, error) {
	if m == nil || m.ListTopCountriesFunc == nil {
		return nil, fmt.Errorf("MockQuerier.ListTopCountriesFunc is nil")
	}
	return m.ListTopCountriesFunc(ctx, arg)
}

func (m *MockQuerier) ListOrdersAboveAverage(ctx context.Context, arg ListOrdersAboveAverageParams) ([]ListOrdersAboveAverageRow, error) {
	if m == nil || m.ListOrdersAboveAverageFunc == nil {
		return nil, fmt.Errorf("MockQuerier.ListOrdersAboveAverageFunc is nil")
	}
	return m.ListOrdersAboveAverageFunc(ctx, arg)
}

func (m *MockQuerier) InsertOrderAudit(ctx context.Context, arg InsertOrderAuditParams) error {
	if m == nil || m.InsertOrderAuditFunc == nil {
		return fmt.Errorf("MockQuerier.InsertOrderAuditFunc is nil")
	}
	return m.InsertOrderAuditFunc(ctx, arg)
}

func (m *MockQuerier) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	if m == nil || m.UpdateOrderStatusFunc == nil {
		return fmt.Errorf("MockQuerier.UpdateOrderStatusFunc is nil")
	}
	return m.UpdateOrderStatusFunc(ctx, arg)
}

func (m *MockQuerier) DeleteOrderEventsBefore(ctx context.Context, arg DeleteOrderEventsBeforeParams) error {
	if m == nil || m.DeleteOrderEventsBeforeFunc == nil {
		return fmt.Errorf("MockQuerier.DeleteOrderEventsBeforeFunc is nil")
	}
	return m.DeleteOrderEventsBeforeFunc(ctx, arg)
}

func (m *MockQuerier) RefreshCountryRollup(ctx context.Context, arg RefreshCountryRollupParams) error {
	if m == nil || m.RefreshCountryRollupFunc == nil {
		return fmt.Errorf("MockQuerier.RefreshCountryRollupFunc is nil")
	}
	return m.RefreshCountryRollupFunc(ctx, arg)
}

func (m *MockQuerier) DropCountryRollupPartition(ctx context.Context, arg DropCountryRollupPartitionParams) error {
	if m == nil || m.DropCountryRollupPartitionFunc == nil {
		return fmt.Errorf("MockQuerier.DropCountryRollupPartitionFunc is nil")
	}
	return m.DropCountryRollupPartitionFunc(ctx, arg)
}

func (m *MockQuerier) ListOrderEventPayloads(ctx context.Context, arg ListOrderEventPayloadsParams) ([]ListOrderEventPayloadsRow, error) {
	if m == nil || m.ListOrderEventPayloadsFunc == nil {
		return nil, fmt.Errorf("MockQuerier.ListOrderEventPayloadsFunc is nil")
	}
	return m.ListOrderEventPayloadsFunc(ctx, arg)
}

func (m *MockQuerier) ListOrdersWithLiteralMarker(ctx context.Context, arg ListOrdersWithLiteralMarkerParams) ([]ListOrdersWithLiteralMarkerRow, error) {
	if m == nil || m.ListOrdersWithLiteralMarkerFunc == nil {
		return nil, fmt.Errorf("MockQuerier.ListOrdersWithLiteralMarkerFunc is nil")
	}
	return m.ListOrdersWithLiteralMarkerFunc(ctx, arg)
}

// New constructs the generated query set. It panics on a nil connection so a
// wiring mistake fails at start time, not on the first query.
func New(conn driver.Conn) *Queries {
	if conn == nil {
		panic("examplequeries.New: ClickHouse connection is nil")
	}
	return &Queries{conn: conn}
}
func chgenNullableParam[T any](value *T) any {
	if value == nil {
		return nil
	}
	return *value
}

// The constants below are the MEASURED range limits of the ClickHouse
// temporal types, taken from ClickHouse 25.8.29.51 through the HTTP
// interface, which does not involve the Go driver. Each limit is the last
// value that the server stores unchanged.
//
// The guards exist because clickhouse-go reports NO error for a value that
// the column cannot hold. Measured with driver v2.47.0, a DateTime64(3) write
// of 2299-12-31 stored 2106-02-07 through conn.Exec and 1900-01-01 through
// the native batch path. Both calls returned nil. The project rule is: never
// silently wrong, thus an unrepresentable value becomes an explicit error.
const (
	chgenDateMinUnix                 = int64(0)
	chgenDateMaxUnix                 = int64(5662310399)
	chgenDate32MinUnix               = int64(-2208988800)
	chgenDate32MaxUnix               = int64(10413791999)
	chgenDateTimeMinUnix             = int64(0)
	chgenDateTimeMaxUnix             = int64(4294967295)
	chgenDateTime64MinUnix           = int64(-2208988800)
	chgenDateTime64MaxUnix           = int64(9223372036)
	chgenDateTime64MaxNanosecond     = int64(854775807)
	chgenDateTime64NanoMinUnix       = int64(-2208988800)
	chgenDateTime64NanoMaxUnix       = int64(9223372036)
	chgenDateTime64NanoMaxNanosecond = int64(854775807)
)

func chgenGuardRange(value time.Time, label, typeName string, minUnix, maxUnix int64) error {
	seconds := value.Unix()
	if seconds < minUnix || seconds > maxUnix {
		return fmt.Errorf(
			"%s: %s cannot hold %s; the representable range is %s to %s",
			label,
			typeName,
			value.UTC().Format(time.RFC3339Nano),
			time.Unix(minUnix, 0).UTC().Format(time.RFC3339),
			time.Unix(maxUnix, 0).UTC().Format(time.RFC3339),
		)
	}
	return nil
}

func chgenGuardDateTime64Range(value time.Time, label, typeName string, minUnix, maxUnix, maxNanosecond int64) error {
	seconds := value.Unix()
	nanosecond := int64(value.Nanosecond())
	if seconds < minUnix || seconds > maxUnix || (seconds == maxUnix && nanosecond > maxNanosecond) {
		return fmt.Errorf(
			"%s: %s cannot hold %s; the representable range is %s to %s",
			label,
			typeName,
			value.UTC().Format(time.RFC3339Nano),
			time.Unix(minUnix, 0).UTC().Format(time.RFC3339),
			time.Unix(maxUnix, maxNanosecond).UTC().Format(time.RFC3339Nano),
		)
	}
	return nil
}

func chgenGuardDate(value time.Time, label string) error {
	return chgenGuardRange(value, label, "Date", chgenDateMinUnix, chgenDateMaxUnix)
}

func chgenGuardDate32(value time.Time, label string) error {
	return chgenGuardRange(value, label, "Date32", chgenDate32MinUnix, chgenDate32MaxUnix)
}

func chgenGuardDateTime(value time.Time, label string) error {
	return chgenGuardRange(value, label, "DateTime", chgenDateTimeMinUnix, chgenDateTimeMaxUnix)
}

// chgenGuardDateTime64 uses the DRIVER limit, not the wider column calendar.
// A DateTime64(3) column holds up to 2299-12-31, but clickhouse-go carries
// every DateTime64 through int64 nanoseconds, so a write of 2299-12-31 stored
// 1900-01-01 00:00:00.291 with err = nil (measured, v2.47.0). Guarding at the
// column limit would pass exactly the values that corrupt.
func chgenGuardDateTime64(value time.Time, label string) error {
	return chgenGuardDateTime64Range(value, label, "DateTime64 through clickhouse-go", chgenDateTime64MinUnix, chgenDateTime64MaxUnix, chgenDateTime64MaxNanosecond)
}

// chgenGuardDateTime64Nano is precision 9, where the server itself raises
// DECIMAL_OVERFLOW past the same nanosecond limit.
func chgenGuardDateTime64Nano(value time.Time, label string) error {
	return chgenGuardDateTime64Range(value, label, "DateTime64(9)", chgenDateTime64NanoMinUnix, chgenDateTime64NanoMaxUnix, chgenDateTime64NanoMaxNanosecond)
}

// chgenCheckScannedTime rejects a DateTime64 that the driver could not carry.
// clickhouse-go converts every DateTime64 through int64 nanoseconds. A stored
// instant after 2262-04-11T23:47:16.854775807Z can arrive as an unrelated
// earlier time with no error. Measured: a stored 2299-12-31 arrives as
// 1715-06-12.
//
// The arriving value does not identify the original instant. This check can
// only refuse the invalid scan. It cannot repair the value.
func chgenCheckScannedTime(value time.Time, label string) error {
	if value.Unix() < chgenReadableMinUnix {
		return fmt.Errorf(
			"%s: the scanned DateTime64 %s is before %s, which means the driver wrapped a stored value that is beyond %s; the value cannot be recovered",
			label,
			value.UTC().Format(time.RFC3339Nano),
			time.Unix(chgenReadableMinUnix, 0).UTC().Format(time.RFC3339),
			time.Unix(chgenReadableMaxUnix, chgenReadableMaxNanosecond).UTC().Format(time.RFC3339Nano),
		)
	}
	return nil
}

const (
	chgenReadableMinUnix       = int64(-2208988800)
	chgenReadableMaxUnix       = int64(9223372036)
	chgenReadableMaxNanosecond = int64(854775807)
)

// OrderedOrderKeysRow is one row supplied to the ordered_order_keys external schema.
type OrderedOrderKeysRow struct {
	Ordinal uint64
	OrderID string
}

func newOrderedOrderKeysRowExternalTable(name string, rows []OrderedOrderKeysRow) (*ext.Table, error) {
	table, err := ext.NewTable(name,
		ext.Column("ordinal", "UInt64"),
		ext.Column("order_id", "String"),
	)
	if err != nil {
		return nil, fmt.Errorf("create external table %s: %w", name, err)
	}
	for rowIndex, row := range rows {
		if err := table.Append(row.Ordinal, row.OrderID); err != nil {
			return nil, fmt.Errorf("append external table %s row %d: %w", name, rowIndex, err)
		}
	}
	return table, nil
}

// ListOrdersRow is one row returned by ListOrders.
type ListOrdersRow struct {
	OrderID      string
	CustomerID   string
	Country      string
	Status       string
	ItemCount    uint32
	TotalAmount  float64
	DiscountCode *string
	TagList      []string
	Attributes   map[string]string
	PlacedAt     time.Time
}

// ListOrdersParams contains the positional arguments for ListOrders.
type ListOrdersParams struct {
	Country string
	Limit   uint64
}

const listOrdersSQL = `SELECT
    order_id,
    customer_id,
    country,
    status,
    item_count,
    total_amount,
    discount_code,
    tag_list,
    attributes,
    placed_at
FROM orders
WHERE country = ?
ORDER BY placed_at DESC
LIMIT ?`

// ListOrders returns typed ClickHouse rows.
func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, listOrdersSQL, arg.Country, arg.Limit)
	if err != nil {
		return nil, fmt.Errorf("ListOrders query: %w", err)
	}
	defer rows.Close()
	result := make([]ListOrdersRow, 0)
	var row ListOrdersRow
	for rows.Next() {
		row = ListOrdersRow{}
		if err := rows.Scan(&row.OrderID, &row.CustomerID, &row.Country, &row.Status, &row.ItemCount, &row.TotalAmount, &row.DiscountCode, &row.TagList, &row.Attributes, &row.PlacedAt); err != nil {
			return nil, fmt.Errorf("ListOrders scan: %w", err)
		}
		if err := chgenCheckScannedTime(row.PlacedAt, "PlacedAt"); err != nil {
			return nil, fmt.Errorf("ListOrders: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ListOrders rows: %w", err)
	}
	return result, nil
}

// CountOrdersForCustomerRow is one row returned by CountOrdersForCustomer.
type CountOrdersForCustomerRow struct {
	OrderCount uint64
	TotalSpend float64
}

// CountOrdersForCustomerParams contains the positional arguments for CountOrdersForCustomer.
type CountOrdersForCustomerParams struct {
	CustomerID string
}

const countOrdersForCustomerSQL = `SELECT
    count() AS order_count,
    sum(total_amount) AS total_spend
FROM orders
WHERE customer_id = ?`

// CountOrdersForCustomer returns one typed ClickHouse row.
func (q *Queries) CountOrdersForCustomer(ctx context.Context, arg CountOrdersForCustomerParams) (CountOrdersForCustomerRow, error) {
	var result CountOrdersForCustomerRow
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, countOrdersForCustomerSQL, arg.CustomerID)
	if err != nil {
		return result, fmt.Errorf("CountOrdersForCustomer query: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, fmt.Errorf("CountOrdersForCustomer rows: %w", err)
		}
		return result, fmt.Errorf("CountOrdersForCustomer: no rows")
	}
	if err := rows.Scan(&result.OrderCount, &result.TotalSpend); err != nil {
		return result, fmt.Errorf("CountOrdersForCustomer scan: %w", err)
	}
	return result, nil
}

// ListOrdersByOptionalDiscountRow is one row returned by ListOrdersByOptionalDiscount.
type ListOrdersByOptionalDiscountRow struct {
	OrderID     string
	TotalAmount float64
}

// ListOrdersByOptionalDiscountParams contains the positional arguments for ListOrdersByOptionalDiscount.
type ListOrdersByOptionalDiscountParams struct {
	DiscountCode string
}

const listOrdersByOptionalDiscountSQL = `SELECT
    order_id,
    total_amount
FROM orders
WHERE (? = '' OR discount_code = ?)
ORDER BY order_id`

// ListOrdersByOptionalDiscount returns typed ClickHouse rows.
func (q *Queries) ListOrdersByOptionalDiscount(ctx context.Context, arg ListOrdersByOptionalDiscountParams) ([]ListOrdersByOptionalDiscountRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, listOrdersByOptionalDiscountSQL, arg.DiscountCode, arg.DiscountCode)
	if err != nil {
		return nil, fmt.Errorf("ListOrdersByOptionalDiscount query: %w", err)
	}
	defer rows.Close()
	result := make([]ListOrdersByOptionalDiscountRow, 0)
	var row ListOrdersByOptionalDiscountRow
	for rows.Next() {
		row = ListOrdersByOptionalDiscountRow{}
		if err := rows.Scan(&row.OrderID, &row.TotalAmount); err != nil {
			return nil, fmt.Errorf("ListOrdersByOptionalDiscount scan: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ListOrdersByOptionalDiscount rows: %w", err)
	}
	return result, nil
}

// DrainOrderEventsRow is one row returned by DrainOrderEvents.
type DrainOrderEventsRow struct {
	OrderID    string
	EventType  string
	OccurredAt time.Time
}

// DrainOrderEventsParams contains the positional arguments for DrainOrderEvents.
type DrainOrderEventsParams struct {
	Since time.Time
	Limit *uint64
}

const drainOrderEventsSQL = `SELECT
    order_id,
    event_type,
    occurred_at
FROM order_events
WHERE occurred_at > ?
ORDER BY occurred_at
LIMIT ifNull(?, toUInt64(-1))`

// DrainOrderEvents returns typed ClickHouse rows.
func (q *Queries) DrainOrderEvents(ctx context.Context, arg DrainOrderEventsParams) ([]DrainOrderEventsRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	if err := chgenGuardDateTime64(arg.Since, "Since"); err != nil {
		return nil, fmt.Errorf("DrainOrderEvents: %w", err)
	}
	rows, err := q.conn.Query(ctx, drainOrderEventsSQL, arg.Since, chgenNullableParam(arg.Limit))
	if err != nil {
		return nil, fmt.Errorf("DrainOrderEvents query: %w", err)
	}
	defer rows.Close()
	result := make([]DrainOrderEventsRow, 0)
	var row DrainOrderEventsRow
	for rows.Next() {
		row = DrainOrderEventsRow{}
		if err := rows.Scan(&row.OrderID, &row.EventType, &row.OccurredAt); err != nil {
			return nil, fmt.Errorf("DrainOrderEvents scan: %w", err)
		}
		if err := chgenCheckScannedTime(row.OccurredAt, "OccurredAt"); err != nil {
			return nil, fmt.Errorf("DrainOrderEvents: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("DrainOrderEvents rows: %w", err)
	}
	return result, nil
}

// ListCustomerActivityRow is one row returned by ListCustomerActivity.
type ListCustomerActivityRow struct {
	CustomerID string
	LastSeenAt time.Time
	P95Spend   float64
}

// ListCustomerActivityParams contains the positional arguments for ListCustomerActivity.
type ListCustomerActivityParams struct {
	Country string
}

const listCustomerActivitySQL = `SELECT
    customer_id,
    maxMerge(last_seen_at_state) AS last_seen_at,
    quantileMerge(0.95)(spend_state) AS p95_spend
FROM customer_activity
WHERE country = ?
GROUP BY customer_id
ORDER BY customer_id`

// ListCustomerActivity returns typed ClickHouse rows.
func (q *Queries) ListCustomerActivity(ctx context.Context, arg ListCustomerActivityParams) ([]ListCustomerActivityRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, listCustomerActivitySQL, arg.Country)
	if err != nil {
		return nil, fmt.Errorf("ListCustomerActivity query: %w", err)
	}
	defer rows.Close()
	result := make([]ListCustomerActivityRow, 0)
	var row ListCustomerActivityRow
	for rows.Next() {
		row = ListCustomerActivityRow{}
		if err := rows.Scan(&row.CustomerID, &row.LastSeenAt, &row.P95Spend); err != nil {
			return nil, fmt.Errorf("ListCustomerActivity scan: %w", err)
		}
		if err := chgenCheckScannedTime(row.LastSeenAt, "LastSeenAt"); err != nil {
			return nil, fmt.Errorf("ListCustomerActivity: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ListCustomerActivity rows: %w", err)
	}
	return result, nil
}

// ListOrdersForKeysRow is one row returned by ListOrdersForKeys.
type ListOrdersForKeysRow struct {
	OrderID     string
	TotalAmount float64
}

// ListOrdersForKeysParams contains the positional arguments for ListOrdersForKeys.
type ListOrdersForKeysParams struct {
	OrderedOrderKeys []OrderedOrderKeysRow
}

const listOrdersForKeysSQL = `SELECT
    o.order_id,
    o.total_amount
FROM orders AS o
INNER JOIN ordered_order_keys AS requested
    ON requested.order_id = o.order_id
ORDER BY requested.ordinal`

// ListOrdersForKeys returns typed ClickHouse rows.
func (q *Queries) ListOrdersForKeys(ctx context.Context, arg ListOrdersForKeysParams) ([]ListOrdersForKeysRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	externalTables := make([]*ext.Table, 0, 1)
	externalTable0, err := newOrderedOrderKeysRowExternalTable("ordered_order_keys", arg.OrderedOrderKeys)
	if err != nil {
		return nil, fmt.Errorf("ListOrdersForKeys: %w", err)
	}
	externalTables = append(externalTables, externalTable0)
	ctx = clickhouse.Context(ctx, clickhouse.WithExternalTable(externalTables...))
	rows, err := q.conn.Query(ctx, listOrdersForKeysSQL)
	if err != nil {
		return nil, fmt.Errorf("ListOrdersForKeys query: %w", err)
	}
	defer rows.Close()
	result := make([]ListOrdersForKeysRow, 0)
	var row ListOrdersForKeysRow
	for rows.Next() {
		row = ListOrdersForKeysRow{}
		if err := rows.Scan(&row.OrderID, &row.TotalAmount); err != nil {
			return nil, fmt.Errorf("ListOrdersForKeys scan: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ListOrdersForKeys rows: %w", err)
	}
	return result, nil
}

// ListOrdersIncludedExcludedRow is one row returned by ListOrdersIncludedExcluded.
type ListOrdersIncludedExcludedRow struct {
	OrderID string
	Country string
}

// ListOrdersIncludedExcludedParams contains the positional arguments for ListOrdersIncludedExcluded.
type ListOrdersIncludedExcludedParams struct {
	IncludedKeys []OrderedOrderKeysRow
	ExcludedKeys []OrderedOrderKeysRow
}

const listOrdersIncludedExcludedSQL = `SELECT
    o.order_id,
    o.country
FROM orders AS o
INNER JOIN includedKeys AS included
    ON included.order_id = o.order_id
LEFT JOIN excludedKeys AS excluded
    ON excluded.order_id = o.order_id
WHERE excluded.order_id = ''
ORDER BY included.ordinal`

// ListOrdersIncludedExcluded returns typed ClickHouse rows.
func (q *Queries) ListOrdersIncludedExcluded(ctx context.Context, arg ListOrdersIncludedExcludedParams) ([]ListOrdersIncludedExcludedRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	externalTables := make([]*ext.Table, 0, 2)
	externalTable0, err := newOrderedOrderKeysRowExternalTable("includedKeys", arg.IncludedKeys)
	if err != nil {
		return nil, fmt.Errorf("ListOrdersIncludedExcluded: %w", err)
	}
	externalTables = append(externalTables, externalTable0)
	externalTable1, err := newOrderedOrderKeysRowExternalTable("excludedKeys", arg.ExcludedKeys)
	if err != nil {
		return nil, fmt.Errorf("ListOrdersIncludedExcluded: %w", err)
	}
	externalTables = append(externalTables, externalTable1)
	ctx = clickhouse.Context(ctx, clickhouse.WithExternalTable(externalTables...))
	rows, err := q.conn.Query(ctx, listOrdersIncludedExcludedSQL)
	if err != nil {
		return nil, fmt.Errorf("ListOrdersIncludedExcluded query: %w", err)
	}
	defer rows.Close()
	result := make([]ListOrdersIncludedExcludedRow, 0)
	var row ListOrdersIncludedExcludedRow
	for rows.Next() {
		row = ListOrdersIncludedExcludedRow{}
		if err := rows.Scan(&row.OrderID, &row.Country); err != nil {
			return nil, fmt.Errorf("ListOrdersIncludedExcluded scan: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ListOrdersIncludedExcluded rows: %w", err)
	}
	return result, nil
}

// ListOrdersForKeysWithHintRow is one row returned by ListOrdersForKeysWithHint.
type ListOrdersForKeysWithHintRow struct {
	OrderID string
	Status  string
}

// ListOrdersForKeysWithHintParams contains the positional arguments for ListOrdersForKeysWithHint.
type ListOrdersForKeysWithHintParams struct {
	RequestedKeys []OrderedOrderKeysRow
}

const listOrdersForKeysWithHintSQL = `SELECT
    o.order_id,
    o.status
FROM orders AS o
INNER JOIN requestedKeys AS requested
    ON requested.order_id = o.order_id
ORDER BY requested.ordinal`

// ListOrdersForKeysWithHint returns typed ClickHouse rows.
func (q *Queries) ListOrdersForKeysWithHint(ctx context.Context, arg ListOrdersForKeysWithHintParams) ([]ListOrdersForKeysWithHintRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	externalTables := make([]*ext.Table, 0, 1)
	externalTable0, err := newOrderedOrderKeysRowExternalTable("requestedKeys", arg.RequestedKeys)
	if err != nil {
		return nil, fmt.Errorf("ListOrdersForKeysWithHint: %w", err)
	}
	externalTables = append(externalTables, externalTable0)
	ctx = clickhouse.Context(ctx, clickhouse.WithExternalTable(externalTables...))
	rows, err := q.conn.Query(ctx, listOrdersForKeysWithHintSQL)
	if err != nil {
		return nil, fmt.Errorf("ListOrdersForKeysWithHint query: %w", err)
	}
	defer rows.Close()
	result := make([]ListOrdersForKeysWithHintRow, 0, len(arg.RequestedKeys))
	var row ListOrdersForKeysWithHintRow
	for rows.Next() {
		row = ListOrdersForKeysWithHintRow{}
		if err := rows.Scan(&row.OrderID, &row.Status); err != nil {
			return nil, fmt.Errorf("ListOrdersForKeysWithHint scan: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ListOrdersForKeysWithHint rows: %w", err)
	}
	return result, nil
}

// ListTopCountriesRow is one row returned by ListTopCountries.
type ListTopCountriesRow struct {
	Country    string
	Revenue    float64
	OrderCount uint64
}

// ListTopCountriesParams contains the positional arguments for ListTopCountries.
type ListTopCountriesParams struct {
	Since time.Time
	Limit uint64
}

const listTopCountriesSQL = `WITH recent AS (
    SELECT
        country,
        total_amount
    FROM orders
    WHERE placed_at >= ?
)
SELECT
    recent.country AS country,
    sum(recent.total_amount) AS revenue,
    count() AS order_count
FROM recent
GROUP BY recent.country
ORDER BY revenue DESC
LIMIT ?`

// ListTopCountries returns typed ClickHouse rows.
func (q *Queries) ListTopCountries(ctx context.Context, arg ListTopCountriesParams) ([]ListTopCountriesRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	if err := chgenGuardDateTime64(arg.Since, "Since"); err != nil {
		return nil, fmt.Errorf("ListTopCountries: %w", err)
	}
	rows, err := q.conn.Query(ctx, listTopCountriesSQL, arg.Since, arg.Limit)
	if err != nil {
		return nil, fmt.Errorf("ListTopCountries query: %w", err)
	}
	defer rows.Close()
	result := make([]ListTopCountriesRow, 0)
	var row ListTopCountriesRow
	for rows.Next() {
		row = ListTopCountriesRow{}
		if err := rows.Scan(&row.Country, &row.Revenue, &row.OrderCount); err != nil {
			return nil, fmt.Errorf("ListTopCountries scan: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ListTopCountries rows: %w", err)
	}
	return result, nil
}

// ListOrdersAboveAverageRow is one row returned by ListOrdersAboveAverage.
type ListOrdersAboveAverageRow struct {
	OrderID     string
	TotalAmount float64
	EventTotal  *uint64
}

// ListOrdersAboveAverageParams contains the positional arguments for ListOrdersAboveAverage.
type ListOrdersAboveAverageParams struct {
	Limit uint64
}

const listOrdersAboveAverageSQL = `WITH (
    SELECT avg(total_amount) AS value FROM orders
) AS avg_amount
SELECT
    order_id,
    total_amount,
    (SELECT count() FROM order_events) AS event_total
FROM orders
WHERE total_amount > avg_amount
ORDER BY total_amount DESC
LIMIT ?`

// ListOrdersAboveAverage returns typed ClickHouse rows.
func (q *Queries) ListOrdersAboveAverage(ctx context.Context, arg ListOrdersAboveAverageParams) ([]ListOrdersAboveAverageRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, listOrdersAboveAverageSQL, arg.Limit)
	if err != nil {
		return nil, fmt.Errorf("ListOrdersAboveAverage query: %w", err)
	}
	defer rows.Close()
	result := make([]ListOrdersAboveAverageRow, 0)
	var row ListOrdersAboveAverageRow
	for rows.Next() {
		row = ListOrdersAboveAverageRow{}
		if err := rows.Scan(&row.OrderID, &row.TotalAmount, &row.EventTotal); err != nil {
			return nil, fmt.Errorf("ListOrdersAboveAverage scan: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ListOrdersAboveAverage rows: %w", err)
	}
	return result, nil
}

// InsertOrderAuditParams contains the positional arguments for InsertOrderAudit.
type InsertOrderAuditParams struct {
	OrderID   string
	Actor     string
	Note      *string
	WrittenAt time.Time
}

const insertOrderAuditSQL = `INSERT INTO order_audit (order_id, actor, note, written_at)
VALUES (?, ?, ?, ?)`

// insertOrderAuditBatchSQL is the prefix that PrepareBatch takes. The native batch
// path keeps the sub-second fraction of a time.Time that the client-side text
// interpolation of conn.Exec drops.
const insertOrderAuditBatchSQL = "INSERT INTO order_audit (order_id, actor, note, written_at)"

// InsertOrderAudit executes the annotated ClickHouse statement.
func (q *Queries) InsertOrderAudit(ctx context.Context, arg InsertOrderAuditParams) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if err := chgenGuardDateTime64(arg.WrittenAt, "WrittenAt"); err != nil {
		return fmt.Errorf("InsertOrderAudit: %w", err)
	}
	batch, err := q.conn.PrepareBatch(ctx, insertOrderAuditBatchSQL)
	if err != nil {
		return fmt.Errorf("InsertOrderAudit prepare batch: %w", err)
	}
	if err := batch.Append(arg.OrderID, arg.Actor, arg.Note, arg.WrittenAt); err != nil {
		return fmt.Errorf("InsertOrderAudit append: %w", err)
	}
	if err := batch.Send(); err != nil {
		return fmt.Errorf("InsertOrderAudit send: %w", err)
	}
	return nil
}

// UpdateOrderStatusParams contains the positional arguments for UpdateOrderStatus.
type UpdateOrderStatusParams struct {
	Status  string
	OrderID string
}

const updateOrderStatusSQL = `ALTER TABLE orders
UPDATE status = ?
WHERE order_id = ?`

// UpdateOrderStatus executes the annotated ClickHouse statement.
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	if ctx == nil {
		ctx = context.Background()
	}
	return q.conn.Exec(ctx, updateOrderStatusSQL, arg.Status, arg.OrderID)
}

// DeleteOrderEventsBeforeParams contains the positional arguments for DeleteOrderEventsBefore.
type DeleteOrderEventsBeforeParams struct {
	Before time.Time
}

const deleteOrderEventsBeforeSQL = `ALTER TABLE order_events
DELETE WHERE occurred_at < ?`

// DeleteOrderEventsBefore executes the annotated ClickHouse statement.
func (q *Queries) DeleteOrderEventsBefore(ctx context.Context, arg DeleteOrderEventsBeforeParams) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if err := chgenGuardDateTime64(arg.Before, "Before"); err != nil {
		return fmt.Errorf("DeleteOrderEventsBefore: %w", err)
	}
	return q.conn.Exec(ctx, deleteOrderEventsBeforeSQL, arg.Before)
}

// RefreshCountryRollupParams contains the positional arguments for RefreshCountryRollup.
type RefreshCountryRollupParams struct {
	WindowStart time.Time
}

const refreshCountryRollupSQL = `INSERT INTO country_rollup (country, order_count, revenue, window_start)
SELECT
    country,
    count() AS order_count,
    sum(total_amount) AS revenue,
    max(placed_at) AS window_start
FROM orders
WHERE placed_at >= ?
GROUP BY country`

// RefreshCountryRollup executes the annotated ClickHouse statement.
func (q *Queries) RefreshCountryRollup(ctx context.Context, arg RefreshCountryRollupParams) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if err := chgenGuardDateTime64(arg.WindowStart, "WindowStart"); err != nil {
		return fmt.Errorf("RefreshCountryRollup: %w", err)
	}
	return q.conn.Exec(ctx, refreshCountryRollupSQL, arg.WindowStart)
}

// DropCountryRollupPartitionParams contains the positional arguments for DropCountryRollupPartition.
type DropCountryRollupPartitionParams struct {
	Partition string
}

const dropCountryRollupPartitionSQL = `ALTER TABLE country_rollup
DROP PARTITION ?`

// DropCountryRollupPartition executes the annotated ClickHouse statement.
func (q *Queries) DropCountryRollupPartition(ctx context.Context, arg DropCountryRollupPartitionParams) error {
	if ctx == nil {
		ctx = context.Background()
	}
	return q.conn.Exec(ctx, dropCountryRollupPartitionSQL, arg.Partition)
}

// ListOrderEventPayloadsRow is one row returned by ListOrderEventPayloads.
type ListOrderEventPayloadsRow struct {
	OrderID    string
	Payload    json.RawMessage
	OccurredAt time.Time
}

// ListOrderEventPayloadsParams contains the positional arguments for ListOrderEventPayloads.
type ListOrderEventPayloadsParams struct {
	OrderID string
}

const listOrderEventPayloadsSQL = `SELECT
    order_id,
    payload,
    occurred_at
FROM order_events
WHERE order_id = ?
ORDER BY occurred_at`

// ListOrderEventPayloads returns typed ClickHouse rows.
func (q *Queries) ListOrderEventPayloads(ctx context.Context, arg ListOrderEventPayloadsParams) ([]ListOrderEventPayloadsRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, listOrderEventPayloadsSQL, arg.OrderID)
	if err != nil {
		return nil, fmt.Errorf("ListOrderEventPayloads query: %w", err)
	}
	defer rows.Close()
	result := make([]ListOrderEventPayloadsRow, 0)
	var row ListOrderEventPayloadsRow
	for rows.Next() {
		row = ListOrderEventPayloadsRow{}
		if err := rows.Scan(&row.OrderID, &row.Payload, &row.OccurredAt); err != nil {
			return nil, fmt.Errorf("ListOrderEventPayloads scan: %w", err)
		}
		if err := chgenCheckScannedTime(row.OccurredAt, "OccurredAt"); err != nil {
			return nil, fmt.Errorf("ListOrderEventPayloads: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ListOrderEventPayloads rows: %w", err)
	}
	return result, nil
}

// ListOrdersWithLiteralMarkerRow is one row returned by ListOrdersWithLiteralMarker.
type ListOrdersWithLiteralMarkerRow struct {
	OrderID string
	Marker  string
	Status  string
}

// ListOrdersWithLiteralMarkerParams contains the positional arguments for ListOrdersWithLiteralMarker.
type ListOrdersWithLiteralMarkerParams struct {
	CustomerID string
}

const listOrdersWithLiteralMarkerSQL = `SELECT
    order_id,
    'chgen.arg(NotAParameter)' AS marker, -- chgen.arg('AlsoNotAParameter')
    status
FROM orders
WHERE customer_id = ?
ORDER BY order_id`

// ListOrdersWithLiteralMarker returns typed ClickHouse rows.
func (q *Queries) ListOrdersWithLiteralMarker(ctx context.Context, arg ListOrdersWithLiteralMarkerParams) ([]ListOrdersWithLiteralMarkerRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, listOrdersWithLiteralMarkerSQL, arg.CustomerID)
	if err != nil {
		return nil, fmt.Errorf("ListOrdersWithLiteralMarker query: %w", err)
	}
	defer rows.Close()
	result := make([]ListOrdersWithLiteralMarkerRow, 0)
	var row ListOrdersWithLiteralMarkerRow
	for rows.Next() {
		row = ListOrdersWithLiteralMarkerRow{}
		if err := rows.Scan(&row.OrderID, &row.Marker, &row.Status); err != nil {
			return nil, fmt.Errorf("ListOrdersWithLiteralMarker scan: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ListOrdersWithLiteralMarker rows: %w", err)
	}
	return result, nil
}
