// Code generated by chgen; DO NOT EDIT.
//
// The ClickHouse type rules that made this file were measured on
// ClickHouse 25.8.29.51. Another major version can answer a
// different type. chgen works offline and cannot read the version of
// your server, thus this line tells you and enforces nothing.

package golden

import (
	"context"
	"fmt"

	"github.com/ClickHouse/clickhouse-go/v2"
	"github.com/ClickHouse/clickhouse-go/v2/ext"
	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
)

// Queries is the generated ClickHouse query set. The target database is a
// connection property (clickhouse Auth.Database); the SQL never names it.
type Queries struct {
	conn driver.Conn
}

// Querier is the generated query-set contract used by services and tests.
type Querier interface {
	ReadIncludedEvents(ctx context.Context, arg ReadIncludedEventsParams) ([]ReadIncludedEventsRow, error)
}

// MockQuerier is a dependency-free test double for the generated query set.
// Set only the Func fields needed by a test; an unset field returns an error.
type MockQuerier struct {
	ReadIncludedEventsFunc func(ctx context.Context, arg ReadIncludedEventsParams) ([]ReadIncludedEventsRow, error)
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*MockQuerier)(nil)

func (m *MockQuerier) ReadIncludedEvents(ctx context.Context, arg ReadIncludedEventsParams) ([]ReadIncludedEventsRow, error) {
	if m == nil || m.ReadIncludedEventsFunc == nil {
		return nil, fmt.Errorf("MockQuerier.ReadIncludedEventsFunc is nil")
	}
	return m.ReadIncludedEventsFunc(ctx, arg)
}

// New constructs the generated query set. It panics on a nil connection so a
// wiring mistake fails at start time, not on the first query.
func New(conn driver.Conn) *Queries {
	if conn == nil {
		panic("golden.New: ClickHouse connection is nil")
	}
	return &Queries{conn: conn}
}

// OrderedStringKeysRow is one row supplied to the ordered_string_keys external schema.
type OrderedStringKeysRow struct {
	Ordinal uint32
	ID      string
}

func newOrderedStringKeysRowExternalTable(name string, rows []OrderedStringKeysRow) (*ext.Table, error) {
	table, err := ext.NewTable(name,
		ext.Column("ordinal", "UInt32"),
		ext.Column("id", "String"),
	)
	if err != nil {
		return nil, fmt.Errorf("create external table %s: %w", name, err)
	}
	for rowIndex, row := range rows {
		if err := table.Append(row.Ordinal, row.ID); err != nil {
			return nil, fmt.Errorf("append external table %s row %d: %w", name, rowIndex, err)
		}
	}
	return table, nil
}

// ReadIncludedEventsRow is one row returned by ReadIncludedEvents.
type ReadIncludedEventsRow struct {
	ID      string
	Payload string
}

// ReadIncludedEventsParams contains the positional arguments for ReadIncludedEvents.
type ReadIncludedEventsParams struct {
	IncludedKeys []OrderedStringKeysRow
}

const readIncludedEventsSQL = `SELECT events.id AS id, events.payload AS payload
FROM events
INNER JOIN includedKeys AS included
    ON included.id = events.id
ORDER BY included.ordinal;`

// ReadIncludedEvents returns typed ClickHouse rows.
func (q *Queries) ReadIncludedEvents(ctx context.Context, arg ReadIncludedEventsParams) ([]ReadIncludedEventsRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	externalTables := make([]*ext.Table, 0, 1)
	externalTable0, err := newOrderedStringKeysRowExternalTable("includedKeys", arg.IncludedKeys)
	if err != nil {
		return nil, fmt.Errorf("ReadIncludedEvents: %w", err)
	}
	externalTables = append(externalTables, externalTable0)
	ctx = clickhouse.Context(ctx, clickhouse.WithExternalTable(externalTables...))
	rows, err := q.conn.Query(ctx, readIncludedEventsSQL)
	if err != nil {
		return nil, fmt.Errorf("ReadIncludedEvents query: %w", err)
	}
	defer rows.Close()
	result := make([]ReadIncludedEventsRow, 0)
	var row ReadIncludedEventsRow
	for rows.Next() {
		row = ReadIncludedEventsRow{}
		if err := rows.Scan(&row.ID, &row.Payload); err != nil {
			return nil, fmt.Errorf("ReadIncludedEvents scan: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ReadIncludedEvents rows: %w", err)
	}
	return result, nil
}
