// Code generated by chgen; DO NOT EDIT.
//
// The ClickHouse type rules that made this file were measured on
// ClickHouse 25.8.29.51. Another major version can answer a
// different type. chgen works offline and cannot read the version of
// your server, thus this line tells you and enforces nothing.

package golden

import (
	"context"
	"fmt"

	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
)

// Queries is the generated ClickHouse query set. The target database is a
// connection property (clickhouse Auth.Database); the SQL never names it.
type Queries struct {
	conn driver.Conn
}

// Querier is the generated query-set contract used by services and tests.
type Querier interface {
	ReadContainers(ctx context.Context, arg ReadContainersParams) (ReadContainersRow, error)
	ReadTupleElements(ctx context.Context, arg ReadTupleElementsParams) (ReadTupleElementsRow, error)
}

// MockQuerier is a dependency-free test double for the generated query set.
// Set only the Func fields needed by a test; an unset field returns an error.
type MockQuerier struct {
	ReadContainersFunc    func(ctx context.Context, arg ReadContainersParams) (ReadContainersRow, error)
	ReadTupleElementsFunc func(ctx context.Context, arg ReadTupleElementsParams) (ReadTupleElementsRow, error)
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*MockQuerier)(nil)

func (m *MockQuerier) ReadContainers(ctx context.Context, arg ReadContainersParams) (ReadContainersRow, error) {
	if m == nil || m.ReadContainersFunc == nil {
		var zero ReadContainersRow
		return zero, fmt.Errorf("MockQuerier.ReadContainersFunc is nil")
	}
	return m.ReadContainersFunc(ctx, arg)
}

func (m *MockQuerier) ReadTupleElements(ctx context.Context, arg ReadTupleElementsParams) (ReadTupleElementsRow, error) {
	if m == nil || m.ReadTupleElementsFunc == nil {
		var zero ReadTupleElementsRow
		return zero, fmt.Errorf("MockQuerier.ReadTupleElementsFunc is nil")
	}
	return m.ReadTupleElementsFunc(ctx, arg)
}

// New constructs the generated query set. It panics on a nil connection so a
// wiring mistake fails at start time, not on the first query.
func New(conn driver.Conn) *Queries {
	if conn == nil {
		panic("golden.New: ClickHouse connection is nil")
	}
	return &Queries{conn: conn}
}

// ReadContainersRow is one row returned by ReadContainers.
type ReadContainersRow struct {
	TagList      []string
	NestedList   [][]uint32
	AttributeMap map[string]uint64
}

// ReadContainersParams contains the positional arguments for ReadContainers.
type ReadContainersParams struct {
	ID uint64
}

const readContainersSQL = `SELECT
    tags   AS tag_list,
    nested AS nested_list,
    attrs  AS attribute_map
FROM container_probe
WHERE id = ?;`

// ReadContainers returns one typed ClickHouse row.
func (q *Queries) ReadContainers(ctx context.Context, arg ReadContainersParams) (ReadContainersRow, error) {
	var result ReadContainersRow
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, readContainersSQL, arg.ID)
	if err != nil {
		return result, fmt.Errorf("ReadContainers query: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, fmt.Errorf("ReadContainers rows: %w", err)
		}
		return result, fmt.Errorf("ReadContainers: no rows")
	}
	if err := rows.Scan(&result.TagList, &result.NestedList, &result.AttributeMap); err != nil {
		return result, fmt.Errorf("ReadContainers scan: %w", err)
	}
	return result, nil
}

// ReadTupleElementsRow is one row returned by ReadTupleElements.
type ReadTupleElementsRow struct {
	FirstElement    int32
	SecondElement   string
	NamedElement    *int32
	NamedByFunction string
}

// ReadTupleElementsParams contains the positional arguments for ReadTupleElements.
type ReadTupleElementsParams struct {
	ID uint64
}

const readTupleElementsSQL = `SELECT
    pair.1                   AS first_element,
    pair.2                   AS second_element,
    named.a                  AS named_element,
    tupleElement(named, 'b') AS named_by_function
FROM container_probe
WHERE id = ?;`

// ReadTupleElements returns one typed ClickHouse row.
func (q *Queries) ReadTupleElements(ctx context.Context, arg ReadTupleElementsParams) (ReadTupleElementsRow, error) {
	var result ReadTupleElementsRow
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, readTupleElementsSQL, arg.ID)
	if err != nil {
		return result, fmt.Errorf("ReadTupleElements query: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, fmt.Errorf("ReadTupleElements rows: %w", err)
		}
		return result, fmt.Errorf("ReadTupleElements: no rows")
	}
	if err := rows.Scan(&result.FirstElement, &result.SecondElement, &result.NamedElement, &result.NamedByFunction); err != nil {
		return result, fmt.Errorf("ReadTupleElements scan: %w", err)
	}
	return result, nil
}
