// Code generated by chgen; DO NOT EDIT.
//
// The ClickHouse type rules that made this file were measured on
// ClickHouse 25.8.29.51. Another major version can answer a
// different type. chgen works offline and cannot read the version of
// your server, thus this line tells you and enforces nothing.

package golden

import (
	"context"
	"errors"
	"fmt"

	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
)

// ErrNoRows is returned by a :one query when ClickHouse returns no row.
// An aggregate over empty input can still return a row. Use -OrNull aggregates
// for NULL values, or HAVING count() > 0 when absence should produce ErrNoRows.
var ErrNoRows = errors.New("no rows")

// Queries is the generated ClickHouse query set. The target database is a
// connection property (clickhouse Auth.Database); the SQL never names it.
type Queries struct {
	conn driver.Conn
}

// Querier is the generated query-set contract used by services and tests.
type Querier interface {
	ReadFactTableChangeSignature(ctx context.Context, arg ReadFactTableChangeSignatureParams) (ReadFactTableChangeSignatureRow, error)
}

// MockQuerier is a dependency-free test double for the generated query set.
// Set only the Func fields needed by a test; an unset field returns an error.
type MockQuerier struct {
	ReadFactTableChangeSignatureFunc func(ctx context.Context, arg ReadFactTableChangeSignatureParams) (ReadFactTableChangeSignatureRow, error)
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*MockQuerier)(nil)

func (m *MockQuerier) ReadFactTableChangeSignature(ctx context.Context, arg ReadFactTableChangeSignatureParams) (ReadFactTableChangeSignatureRow, error) {
	if m == nil || m.ReadFactTableChangeSignatureFunc == nil {
		var zero ReadFactTableChangeSignatureRow
		return zero, fmt.Errorf("MockQuerier.ReadFactTableChangeSignatureFunc is nil")
	}
	return m.ReadFactTableChangeSignatureFunc(ctx, arg)
}

// New constructs the generated query set. It panics on a nil connection so a
// wiring mistake fails at start time, not on the first query.
func New(conn driver.Conn) *Queries {
	if conn == nil {
		panic("golden.New: ClickHouse connection is nil")
	}
	return &Queries{conn: conn}
}

// ReadFactTableChangeSignatureRow is one row returned by ReadFactTableChangeSignature.
type ReadFactTableChangeSignatureRow struct {
	Signature uint64
}

// ReadFactTableChangeSignatureParams contains the positional arguments for ReadFactTableChangeSignature.
type ReadFactTableChangeSignatureParams struct {
	Table string
}

const readFactTableChangeSignatureSQL = `SELECT toUInt64(sum(cityHash64(partition_id, max_block, mutation))) AS signature
FROM (
    SELECT
        partition_id,
        max(max_block_number) AS max_block,
        max(if(data_version > max_block_number, data_version, 0)) AS mutation
    FROM system.parts
    WHERE database = currentDatabase() AND table = ? AND active
    GROUP BY partition_id
)
SETTINGS log_comment = 'serving_read_change_signature';`

// ReadFactTableChangeSignature returns one typed ClickHouse row.
func (q *Queries) ReadFactTableChangeSignature(ctx context.Context, arg ReadFactTableChangeSignatureParams) (ReadFactTableChangeSignatureRow, error) {
	var result ReadFactTableChangeSignatureRow
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, readFactTableChangeSignatureSQL, arg.Table)
	if err != nil {
		return result, fmt.Errorf("ReadFactTableChangeSignature query: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, fmt.Errorf("ReadFactTableChangeSignature rows: %w", err)
		}
		return result, fmt.Errorf("ReadFactTableChangeSignature: %w", ErrNoRows)
	}
	if err := rows.Scan(&result.Signature); err != nil {
		return result, fmt.Errorf("ReadFactTableChangeSignature scan: %w", err)
	}
	return result, nil
}
