// Command execoraclegate checks an execution-oracle report against the
// committed baseline of accepted finding signatures, and regenerates that
// baseline on request.
//
// Usage:
//
//	go run ./internal/tooling/cmd/execoraclegate -report exec-oracle-report.json
//
//	go run ./internal/tooling/cmd/execoraclegate -update -i-measured-this=25.8.29.51 \
//	    -report exec-oracle-report.json
//
// It exits 0 when the report passes, 1 when the report shows a finding
// signature the baseline does not accept, and 2 when the check cannot
// answer the question, for example when the report is missing, ran zero
// cases, or names a different ClickHouse version than the baseline.
//
// # Why this exists, and why it gates on signatures and never totals
//
// See internal/execoraclereport for the full reasoning. In short: the
// execution oracle runs against a live, non-deterministic server, so a gate
// on a COUNT of findings would go red or green according to how long the
// service container had been running rather than according to the code
// under test. This program instead asks whether the SET of finding
// signatures a run produced is a SUBSET of the set a person has already
// looked at and accepted.
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/IlyaGulya/chgen/internal/execoraclereport"
)

func main() {
	baselinePath := flag.String("baseline", "testdata/execoracle-baseline.json",
		"path of the committed exec-oracle baseline file")
	reportPath := flag.String("report", "", "path of the execution-oracle JSON report to check")
	update := flag.Bool("update", false,
		"write the baseline from the report instead of checking against it; "+
			"needs -i-measured-this as well")
	confirm := flag.String("i-measured-this", "",
		"with -update: the ClickHouse version that the report was measured on. "+
			"It must equal the version inside the report. This keeps the baseline "+
			"from being regenerated by accident")
	note := flag.String("note", "", "with -update: measured reason for each accepted row")
	flag.Parse()

	if *reportPath == "" || flag.NArg() != 0 {
		fmt.Fprintln(os.Stderr,
			"usage: execoraclegate [-baseline path] [-update -i-measured-this <version>] -report path.json")
		os.Exit(2)
	}

	r, err := execoraclereport.Load(*reportPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", *reportPath, err)
		os.Exit(2)
	}
	if r.Cases == 0 {
		fmt.Fprintf(os.Stderr,
			"REFUSED: %s reports 0 cases; an empty read is not a measurement\n", *reportPath)
		os.Exit(2)
	}

	if *update {
		if err := writeBaseline(*baselinePath, *confirm, *note, r); err != nil {
			fmt.Fprintf(os.Stderr, "REFUSED: %v\n", err)
			os.Exit(2)
		}
		return
	}

	baseline, err := execoraclereport.LoadBaseline(*baselinePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "REFUSED: %v\n", err)
		os.Exit(2)
	}

	// The mandatory-signature check is independent of, and runs before,
	// the subset gate below. It must fire even when someone hand-edits
	// the baseline to drop canary_null_zero or unsupported_tuple from
	// Accepted: dropping them from Mandatory too would be a second,
	// separate edit, and the mismatch between the JSON file and
	// execoracle_test.go's own "BLIND ORACLE" t.Fatalf would then be the
	// signal that something is wrong, not a check either side agreed to
	// skip.
	if err := baseline.RequireMandatory(r); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	res, err := baseline.Gate(r)
	if err != nil {
		fmt.Fprintf(os.Stderr, "REFUSED: %v\n", err)
		os.Exit(2)
	}
	fmt.Print(res)
	if !res.OK() {
		fmt.Fprintln(os.Stderr,
			"\nThe execution oracle found a finding signature that the baseline does not "+
				"accept. Either the change under review made chgen answer wrong where it "+
				"answered right before, or the signature is understood and accepted. Read "+
				"the class, then regenerate the baseline on purpose with -update.")
		os.Exit(1)
	}
}

// writeBaseline builds the baseline file from one report.
//
// It refuses unless the caller repeats the ClickHouse version the report
// carries. The flag is not a yes-or-no switch on purpose: a person who
// regenerates a baseline must name the thing they measured, and a person
// who ran the command by mistake cannot name it.
func writeBaseline(path, confirm, note string, r *execoraclereport.Report) error {
	if confirm == "" {
		return fmt.Errorf(
			"-update needs -i-measured-this=<clickhouse-version>. The baseline records the " +
				"measured findings of one pinned server, thus it must never be regenerated by " +
				"a command that a person ran by mistake")
	}
	if confirm != r.CHVersion {
		return fmt.Errorf(
			"-i-measured-this=%q does not equal the ClickHouse version inside the report (%q)",
			confirm, r.CHVersion)
	}
	if note == "" {
		return fmt.Errorf("-update needs -note with the measured reason for each accepted row")
	}

	// Mandatory carries forward the signatures that
	// execoracle_test.go already t.Fatalf's on when absent
	// (canary_null_zero/probe/value_distortion and
	// unsupported_tuple/generation/chgen_unsupported). They are named
	// here, not discovered from the report, because a report that
	// happened to miss one of them would otherwise silently drop it from
	// Mandatory too, which is exactly the failure this field exists to
	// prevent.
	mandatory := []string{
		"arr_arr_int128:generation:chgen_unsupported:row=-1:type=Array(Array(Int128))",
		"arr_int128:generation:chgen_unsupported:row=-1:type=Array(Int128)",
		"arr_int256:generation:chgen_unsupported:row=-1:type=Array(Int256)",
		"arr_uint128:generation:chgen_unsupported:row=-1:type=Array(UInt128)",
		"arr_uint256:generation:chgen_unsupported:row=-1:type=Array(UInt256)",
		"arrnull_int128:generation:chgen_unsupported:row=-1:type=Array(Nullable(Int128))",
		"arrnull_int256:generation:chgen_unsupported:row=-1:type=Array(Nullable(Int256))",
		"arrnull_uint128:generation:chgen_unsupported:row=-1:type=Array(Nullable(UInt128))",
		"arrnull_uint256:generation:chgen_unsupported:row=-1:type=Array(Nullable(UInt256))",
		"bare_int128:generation:chgen_unsupported:row=-1:type=Int128",
		"bare_int256:generation:chgen_unsupported:row=-1:type=Int256",
		"bare_uint128:generation:chgen_unsupported:row=-1:type=UInt128",
		"bare_uint256:generation:chgen_unsupported:row=-1:type=UInt256",
		"canary_null_zero:probe:value_distortion:row=0:type=Nullable(Int32)",
		"mapval_int128:generation:chgen_unsupported:row=-1:type=Map(String, Int128)",
		"mapval_int256:generation:chgen_unsupported:row=-1:type=Map(String, Int256)",
		"mapval_uint128:generation:chgen_unsupported:row=-1:type=Map(String, UInt128)",
		"mapval_uint256:generation:chgen_unsupported:row=-1:type=Map(String, UInt256)",
		"null_int128:generation:chgen_unsupported:row=-1:type=Nullable(Int128)",
		"null_int256:generation:chgen_unsupported:row=-1:type=Nullable(Int256)",
		"null_uint128:generation:chgen_unsupported:row=-1:type=Nullable(UInt128)",
		"null_uint256:generation:chgen_unsupported:row=-1:type=Nullable(UInt256)",
		"unsupported_tuple:generation:chgen_unsupported:row=-1:type=Tuple(Int32, String)",
	}
	runSigs := map[string]bool{}
	for _, s := range execoraclereport.Signatures(r) {
		runSigs[s] = true
	}
	for _, m := range mandatory {
		if !runSigs[m] {
			return fmt.Errorf(
				"the report does not contain the mandatory signature %q; a baseline built "+
					"from this report would silently stop requiring it. Re-run the oracle, or "+
					"fix the regression that made this witness disappear",
				m)
		}
	}

	accepted := execoraclereport.Signatures(r)
	reasons := make(map[string]string, len(accepted))
	for _, signature := range accepted {
		reasons[signature] = note
	}
	b := &execoraclereport.Baseline{
		CHVersion:     r.CHVersion,
		DriverVersion: r.DriverVersion,
		Note:          note,
		Mandatory:     mandatory,
		Accepted:      accepted,
		Reasons:       reasons,
	}
	data, err := b.Marshal()
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s: ClickHouse %s, %d accepted signature(s)\n", path, b.CHVersion, len(b.Accepted))
	for _, s := range b.Accepted {
		fmt.Printf("  %s\n", s)
	}
	return nil
}
