package typespecimen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// Load reads a type specimen catalog.
func Load(path string) (Catalog, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Catalog{}, err
	}
	var catalog Catalog
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&catalog); err != nil {
		return Catalog{}, err
	}
	return catalog, nil
}

// GeneratedGo returns the fixture columns in generated Go source.
func GeneratedGo(packageName string, catalog Catalog) []byte {
	var output strings.Builder
	output.WriteString("// Code generated by typespecimens. DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "package %s\n\n", packageName)
	output.WriteString("const generatedTypeSpecimenColumns = `\n")
	accepted := catalog.AcceptedEntries()
	for index, entry := range accepted {
		comma := ","
		if index == len(accepted)-1 {
			comma = ""
		}
		fmt.Fprintf(&output, "    %s %s%s\n", entry.Column, entry.ObservedType, comma)
	}
	output.WriteString("`\n")
	return []byte(output.String())
}
