// Code generated by chgen; DO NOT EDIT.
//
// The ClickHouse type rules that made this file were measured on
// ClickHouse 25.8.29.51. Another major version can answer a
// different type. chgen works offline and cannot read the version of
// your server, thus this line tells you and enforces nothing.

package golden

import (
	"context"
	"errors"
	"fmt"

	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
	"github.com/shopspring/decimal"
)

// ErrNoRows is returned by a :one query when ClickHouse returns no row.
// An aggregate over empty input can still return a row. Use -OrNull aggregates
// for NULL values, or HAVING count() > 0 when absence should produce ErrNoRows.
var ErrNoRows = errors.New("no rows")

// Queries is the generated ClickHouse query set. The target database is a
// connection property (clickhouse Auth.Database); the SQL never names it.
type Queries struct {
	conn driver.Conn
}

// Querier is the generated query-set contract used by services and tests.
type Querier interface {
	ReadConstructors(ctx context.Context, arg ReadConstructorsParams) (ReadConstructorsRow, error)
}

// MockQuerier is a dependency-free test double for the generated query set.
// Set only the Func fields needed by a test; an unset field returns an error.
type MockQuerier struct {
	ReadConstructorsFunc func(ctx context.Context, arg ReadConstructorsParams) (ReadConstructorsRow, error)
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*MockQuerier)(nil)

func (m *MockQuerier) ReadConstructors(ctx context.Context, arg ReadConstructorsParams) (ReadConstructorsRow, error) {
	if m == nil || m.ReadConstructorsFunc == nil {
		var zero ReadConstructorsRow
		return zero, fmt.Errorf("MockQuerier.ReadConstructorsFunc is nil")
	}
	return m.ReadConstructorsFunc(ctx, arg)
}

// New constructs the generated query set. It panics on a nil connection so a
// wiring mistake fails at start time, not on the first query.
func New(conn driver.Conn) *Queries {
	if conn == nil {
		panic("golden.New: ClickHouse connection is nil")
	}
	return &Queries{conn: conn}
}

// ReadConstructorsRow is one row returned by ReadConstructors.
type ReadConstructorsRow struct {
	FixedString        string
	DecimalFromInt     decimal.Decimal
	SmallDecimal       decimal.Decimal
	IntOrNull          *int32
	IntOrZero          int32
	FromLowCardinality int64
	FromNullable       *uint64
}

// ReadConstructorsParams contains the positional arguments for ReadConstructors.
type ReadConstructorsParams struct {
	ID uint64
}

const readConstructorsSQL = `SELECT
    toFixedString(s, 8)    AS fixed_string,
    toDecimal64(i32, 4)    AS decimal_from_int,
    toDecimal32(u32, 2)    AS small_decimal,
    toInt32OrNull(s)       AS int_or_null,
    toInt32OrZero(s)       AS int_or_zero,
    toInt64(lc)            AS from_low_cardinality,
    toUInt64OrNull(ns)     AS from_nullable
FROM constructor_probe
WHERE id = ?;`

// ReadConstructors returns one typed ClickHouse row.
func (q *Queries) ReadConstructors(ctx context.Context, arg ReadConstructorsParams) (ReadConstructorsRow, error) {
	var result ReadConstructorsRow
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, readConstructorsSQL, arg.ID)
	if err != nil {
		return result, fmt.Errorf("ReadConstructors query: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, fmt.Errorf("ReadConstructors rows: %w", err)
		}
		return result, fmt.Errorf("ReadConstructors: %w", ErrNoRows)
	}
	if err := rows.Scan(&result.FixedString, &result.DecimalFromInt, &result.SmallDecimal, &result.IntOrNull, &result.IntOrZero, &result.FromLowCardinality, &result.FromNullable); err != nil {
		return result, fmt.Errorf("ReadConstructors scan: %w", err)
	}
	return result, nil
}
