// Code generated by chgen; DO NOT EDIT.
//
// The ClickHouse type rules that made this file were measured on
// ClickHouse 25.8.29.51. Another major version can answer a
// different type. chgen works offline and cannot read the version of
// your server, thus this line tells you and enforces nothing.

package golden

import (
	"context"
	"fmt"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
)

// Queries is the generated ClickHouse query set. The target database is a
// connection property (clickhouse Auth.Database); the SQL never names it.
type Queries struct {
	conn driver.Conn
}

// Querier is the generated query-set contract used by services and tests.
type Querier interface {
	RefreshRollup(ctx context.Context, arg RefreshRollupParams) error
}

// MockQuerier is a dependency-free test double for the generated query set.
// Set only the Func fields needed by a test; an unset field returns an error.
type MockQuerier struct {
	RefreshRollupFunc func(ctx context.Context, arg RefreshRollupParams) error
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*MockQuerier)(nil)

func (m *MockQuerier) RefreshRollup(ctx context.Context, arg RefreshRollupParams) error {
	if m == nil || m.RefreshRollupFunc == nil {
		return fmt.Errorf("MockQuerier.RefreshRollupFunc is nil")
	}
	return m.RefreshRollupFunc(ctx, arg)
}

// New constructs the generated query set. It panics on a nil connection so a
// wiring mistake fails at start time, not on the first query.
func New(conn driver.Conn) *Queries {
	if conn == nil {
		panic("golden.New: ClickHouse connection is nil")
	}
	return &Queries{conn: conn}
}

// The constants below are the MEASURED range limits of the ClickHouse
// temporal types, taken from ClickHouse 25.8.29.51 through the HTTP
// interface, which does not involve the Go driver. Each limit is the last
// value that the server stores unchanged.
//
// The guards exist because clickhouse-go reports NO error for a value that
// the column cannot hold. Measured with driver v2.47.0, a DateTime64(3) write
// of 2299-12-31 stored 2106-02-07 through conn.Exec and 1900-01-01 through
// the native batch path. Both calls returned nil. The project rule is: never
// silently wrong, thus an unrepresentable value becomes an explicit error.
const (
	chgenDateMinUnix           = int64(0)
	chgenDateMaxUnix           = int64(5662310399)
	chgenDate32MinUnix         = int64(-2208988800)
	chgenDate32MaxUnix         = int64(10413791999)
	chgenDateTimeMinUnix       = int64(0)
	chgenDateTimeMaxUnix       = int64(4294967295)
	chgenDateTime64MinUnix     = int64(-2208988800)
	chgenDateTime64MaxUnix     = int64(9223372036)
	chgenDateTime64NanoMinUnix = int64(-2208988800)
	chgenDateTime64NanoMaxUnix = int64(9223372036)
)

func chgenGuardRange(value time.Time, label, typeName string, minUnix, maxUnix int64) error {
	seconds := value.Unix()
	if seconds < minUnix || seconds > maxUnix {
		return fmt.Errorf(
			"%s: %s cannot hold %s; the representable range is %s to %s",
			label,
			typeName,
			value.UTC().Format(time.RFC3339Nano),
			time.Unix(minUnix, 0).UTC().Format(time.RFC3339),
			time.Unix(maxUnix, 0).UTC().Format(time.RFC3339),
		)
	}
	return nil
}

func chgenGuardDate(value time.Time, label string) error {
	return chgenGuardRange(value, label, "Date", chgenDateMinUnix, chgenDateMaxUnix)
}

func chgenGuardDate32(value time.Time, label string) error {
	return chgenGuardRange(value, label, "Date32", chgenDate32MinUnix, chgenDate32MaxUnix)
}

func chgenGuardDateTime(value time.Time, label string) error {
	return chgenGuardRange(value, label, "DateTime", chgenDateTimeMinUnix, chgenDateTimeMaxUnix)
}

// chgenGuardDateTime64 uses the DRIVER limit, not the wider column calendar.
// A DateTime64(3) column holds up to 2299-12-31, but clickhouse-go carries
// every DateTime64 through int64 nanoseconds, so a write of 2299-12-31 stored
// 1900-01-01 00:00:00.291 with err = nil (measured, v2.47.0). Guarding at the
// column limit would pass exactly the values that corrupt.
func chgenGuardDateTime64(value time.Time, label string) error {
	return chgenGuardRange(value, label, "DateTime64 through clickhouse-go", chgenDateTime64MinUnix, chgenDateTime64MaxUnix)
}

// chgenGuardDateTime64Nano is precision 9, where the server itself raises
// DECIMAL_OVERFLOW past the same nanosecond limit.
func chgenGuardDateTime64Nano(value time.Time, label string) error {
	return chgenGuardRange(value, label, "DateTime64(9)", chgenDateTime64NanoMinUnix, chgenDateTime64NanoMaxUnix)
}

// RefreshRollupParams contains the positional arguments for RefreshRollup.
type RefreshRollupParams struct {
	Since time.Time
}

const refreshRollupSQL = `INSERT INTO metric_rollup (day, max_state, sum_state, uniq_state)
SELECT
    day,
    maxState(value),
    sumState(amount),
    uniqState(kind)
FROM metric_events
WHERE day >= ?
GROUP BY day;`

// RefreshRollup executes the annotated ClickHouse statement.
func (q *Queries) RefreshRollup(ctx context.Context, arg RefreshRollupParams) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if err := chgenGuardDate(arg.Since, "Since"); err != nil {
		return fmt.Errorf("RefreshRollup: %w", err)
	}
	return q.conn.Exec(ctx, refreshRollupSQL, arg.Since)
}
