// Code generated by chgen; DO NOT EDIT.
//
// The ClickHouse type rules that made this file were measured on
// ClickHouse 25.8.29.51. Another major version can answer a
// different type. chgen works offline and cannot read the version of
// your server, thus this line tells you and enforces nothing.

package golden

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
)

// ErrNoRows is returned by a :one query when ClickHouse returns no row.
// An aggregate over empty input can still return a row. Use -OrNull aggregates
// for NULL values, or HAVING count() > 0 when absence should produce ErrNoRows.
var ErrNoRows = errors.New("no rows")

// Queries is the generated ClickHouse query set. The target database is a
// connection property (clickhouse Auth.Database); the SQL never names it.
type Queries struct {
	conn driver.Conn
}

// Querier is the generated query-set contract used by services and tests.
type Querier interface {
	ReadMergedStates(ctx context.Context, arg ReadMergedStatesParams) ([]ReadMergedStatesRow, error)
	ReadConditionalAggregates(ctx context.Context, arg ReadConditionalAggregatesParams) (ReadConditionalAggregatesRow, error)
}

// MockQuerier is a dependency-free test double for the generated query set.
// Set only the Func fields needed by a test; an unset field returns an error.
type MockQuerier struct {
	ReadMergedStatesFunc          func(ctx context.Context, arg ReadMergedStatesParams) ([]ReadMergedStatesRow, error)
	ReadConditionalAggregatesFunc func(ctx context.Context, arg ReadConditionalAggregatesParams) (ReadConditionalAggregatesRow, error)
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*MockQuerier)(nil)

func (m *MockQuerier) ReadMergedStates(ctx context.Context, arg ReadMergedStatesParams) ([]ReadMergedStatesRow, error) {
	if m == nil || m.ReadMergedStatesFunc == nil {
		return nil, fmt.Errorf("MockQuerier.ReadMergedStatesFunc is nil")
	}
	return m.ReadMergedStatesFunc(ctx, arg)
}

func (m *MockQuerier) ReadConditionalAggregates(ctx context.Context, arg ReadConditionalAggregatesParams) (ReadConditionalAggregatesRow, error) {
	if m == nil || m.ReadConditionalAggregatesFunc == nil {
		var zero ReadConditionalAggregatesRow
		return zero, fmt.Errorf("MockQuerier.ReadConditionalAggregatesFunc is nil")
	}
	return m.ReadConditionalAggregatesFunc(ctx, arg)
}

// New constructs the generated query set. It panics on a nil connection so a
// wiring mistake fails at start time, not on the first query.
func New(conn driver.Conn) *Queries {
	if conn == nil {
		panic("golden.New: ClickHouse connection is nil")
	}
	return &Queries{conn: conn}
}

// ReadMergedStatesRow is one row returned by ReadMergedStates.
type ReadMergedStatesRow struct {
	Day       time.Time
	MaxValue  uint32
	SumValue  float64
	UniqValue uint64
}

// ReadMergedStatesParams contains the positional arguments for ReadMergedStates.
type ReadMergedStatesParams struct {
}

const readMergedStatesSQL = `SELECT
    day                    AS day,
    maxMerge(max_state)    AS max_value,
    sumMerge(sum_state)    AS sum_value,
    uniqMerge(uniq_state)  AS uniq_value
FROM metric_rollup
GROUP BY day;`

// ReadMergedStates returns typed ClickHouse rows.
func (q *Queries) ReadMergedStates(ctx context.Context, arg ReadMergedStatesParams) ([]ReadMergedStatesRow, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, readMergedStatesSQL)
	if err != nil {
		return nil, fmt.Errorf("ReadMergedStates query: %w", err)
	}
	defer rows.Close()
	result := make([]ReadMergedStatesRow, 0)
	var row ReadMergedStatesRow
	for rows.Next() {
		row = ReadMergedStatesRow{}
		if err := rows.Scan(&row.Day, &row.MaxValue, &row.SumValue, &row.UniqValue); err != nil {
			return nil, fmt.Errorf("ReadMergedStates scan: %w", err)
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ReadMergedStates rows: %w", err)
	}
	return result, nil
}

// ReadConditionalAggregatesRow is one row returned by ReadConditionalAggregates.
type ReadConditionalAggregatesRow struct {
	BigCount    uint64
	BigSum      float64
	ReadAverage float64
}

// ReadConditionalAggregatesParams contains the positional arguments for ReadConditionalAggregates.
type ReadConditionalAggregatesParams struct {
}

const readConditionalAggregatesSQL = `SELECT
    countIf(value > 10)          AS big_count,
    sumIf(amount, value > 10)    AS big_sum,
    avgIf(amount, kind = 'read') AS read_average
FROM metric_events;`

// ReadConditionalAggregates returns one typed ClickHouse row.
func (q *Queries) ReadConditionalAggregates(ctx context.Context, arg ReadConditionalAggregatesParams) (ReadConditionalAggregatesRow, error) {
	var result ReadConditionalAggregatesRow
	if ctx == nil {
		ctx = context.Background()
	}
	rows, err := q.conn.Query(ctx, readConditionalAggregatesSQL)
	if err != nil {
		return result, fmt.Errorf("ReadConditionalAggregates query: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, fmt.Errorf("ReadConditionalAggregates rows: %w", err)
		}
		return result, fmt.Errorf("ReadConditionalAggregates: %w", ErrNoRows)
	}
	if err := rows.Scan(&result.BigCount, &result.BigSum, &result.ReadAverage); err != nil {
		return result, fmt.Errorf("ReadConditionalAggregates scan: %w", err)
	}
	return result, nil
}
